CREATE TABLE HL_PERSON
(
	ID						BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	PINFL					VARCHAR(14),
    INN						VARCHAR(9),
	
	DOCUMENT_TYPE_ID		INT NOT NULL,
	DOCUMENT_SERIA			VARCHAR(50) NOT NULL,
	DOCUMENT_NUMBER			VARCHAR(50) NOT NULL,
	DOCUMENT_START_ON		DATE,
	DOCUMENT_END_ON			DATE,
	LAST_NAME				VARCHAR(100) NOT NULL,
	FIRST_NAME				VARCHAR(100) NOT NULL,
	MIDDLE_NAME				VARCHAR(100),
	FULL_NAME				VARCHAR(100) NOT NULL,
	BIRTH_ON				DATE NOT NULL,
	GENDER_ID				INT,
	BIRTH_COUNTRY_ID		INT,
	BIRTH_REGION_ID			INT,
	BIRTH_DISTRICT_ID		INT,
	CITIZENSHIP_ID			INT,
	LIVING_REGION_ID		INT,
	LIVING_DISTRICT_ID		INT,
	FILE_ID					UUID,--Person rasmi
	FILE_NAME				VARCHAR(250),

	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,	
	STATE_ID				INT NOT NULL,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,
	BRANCH_ID 				INT,
    
	CONSTRAINT FK_DOCUMENT_TYPE_ID		
		FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES ENUM_DOCUMENT_TYPE ( ID ),
	CONSTRAINT FK_BIRTH_COUNTRY_ID	
		FOREIGN KEY (BIRTH_COUNTRY_ID) REFERENCES INFO_COUNTRY ( ID ),
	CONSTRAINT FK_BIRTH_REGION_ID		
		FOREIGN KEY (BIRTH_REGION_ID) REFERENCES INFO_REGION ( ID ),
	CONSTRAINT FK_BIRTH_DISTRICT_ID		
		FOREIGN KEY (BIRTH_DISTRICT_ID) REFERENCES INFO_DISTRICT ( ID ),
	CONSTRAINT FK_CITIZENSHIP_ID		
		FOREIGN KEY (CITIZENSHIP_ID ) REFERENCES INFO_CITIZENSHIP ( ID ),
    CONSTRAINT FK_STATE_ID				
		FOREIGN KEY (STATE_ID) REFERENCES ENUM_STATE ( ID ),
	CONSTRAINT FK_LIVING_REGION_ID	
		FOREIGN KEY (LIVING_REGION_ID) REFERENCES INFO_REGION ( ID ),
	CONSTRAINT FK_LIVING_DISTRICT_ID	
		FOREIGN KEY (LIVING_DISTRICT_ID) REFERENCES INFO_DISTRICT ( ID ),
    CONSTRAINT FK_GENDER_ID			
		FOREIGN KEY (GENDER_ID) REFERENCES ENUM_GENDER ( ID ),
	CONSTRAINT FK_BRANCH_ID 
		FOREIGN KEY (BRANCH_ID) REFERENCES HL_BRANCH (ID) ON DELETE SET NULL

);

CREATE UNIQUE INDEX HL_PERSON_UNIQUE_INDEX_PINFL ON HL_PERSON (PINFL)
  WHERE PINFL IS NOT NULL;
  
CREATE UNIQUE INDEX HL_PERSON_UNIQUE_INDEX_INN ON HL_PERSON (INN)
  WHERE INN IS NOT NULL;