CREATE TABLE SYS_ROLE_PERMISSION (
    ID 			INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    ROLE_ID 	INT NOT NULL,
    PERMISSION_ID 	INT NOT NULL,
    
	IS_DELETED	BOOL NOT NULL DEFAULT FALSE,	
    CREATED_BY  INT NOT NULL,
    MODIFIED_BY INT,
    CREATED_AT  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,

    CONSTRAINT FK_ROLE_ID 
		FOREIGN KEY (ROLE_ID)
			REFERENCES SYS_ROLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PERMISSION_ID 
		FOREIGN KEY (PERMISSION_ID)
			REFERENCES SYS_PERMISSION(ID),
    CONSTRAINT FK_CREATED_BY
		FOREIGN KEY (CREATED_BY)
			REFERENCES SYS_USER(ID)
);
