CREATE TABLE HL_DEVICE
(
    ID                  	INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    UNIQUE_NUMBER       	VARCHAR(100) NOT NULL,
    SERIAL_NUMBER       	VARCHAR(100) NOT NULL,
	BRANCH_ID				INT NOT NULL,

	DEVICE_TYPE_ID			INT NOT NULL,
	DEVICE_MODEL_ID			INT NOT NULL,
    MANUFACTURER_ID			BIGINT,
	SERVICE_CONTRACTOR_ID	BIGINT,
	RESPONSIBLE_PERSON_ID	BIGINT NOT NULL,
	
	STATE_ID				INT NOT NULL,	
	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT    			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT NULL,
	MODIFIED_AT   			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   			INT,

	CONSTRAINT FK_MANUFACTURER_ID
		FOREIGN KEY (MANUFACTURER_ID)
			REFERENCES INFO_CONTRACTOR (ID),
	CONSTRAINT FK_SERVICE_CONTRACTOR_ID
		FOREIGN KEY (SERVICE_CONTRACTOR_ID)
			REFERENCES INFO_CONTRACTOR (ID),			
	CONSTRAINT FK_DEVICE_TYPE_ID
		FOREIGN KEY (DEVICE_TYPE_ID)
			REFERENCES INFO_DEVICE_TYPE (ID),		
	CONSTRAINT FK_DEVICE_MODEL_ID
		FOREIGN KEY (DEVICE_MODEL_ID)
			REFERENCES INFO_DEVICE_MODEL (ID),	
	CONSTRAINT FK_RESPONSIBLE_PERSON_ID
		FOREIGN KEY (RESPONSIBLE_PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID)
);

CREATE UNIQUE INDEX UIX__HL_DEV__STID_UNIQNUM
	ON HL_DEVICE (STATE_ID,UNIQUE_NUMBER)
	WHERE STATE_ID = 1;

CREATE UNIQUE INDEX UIX__HL_DEV__STID_SERNUM
	ON HL_DEVICE (STATE_ID,SERIAL_NUMBER)
	WHERE STATE_ID = 1;