CREATE TABLE INFO_DEVICE_PART --Узел/модуль УС
(
	ID							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	ORDER_CODE					VARCHAR(50),
	
	SHORT_NAME					VARCHAR(250) NOT NULL,
	FULL_NAME					VARCHAR(500) NOT NULL,
	DEVICE_TYPE_ID				INT NOT NULL,
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATE_ID					INT NOT NULL,	
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (id),
	CONSTRAINT FK_DEVICE_TYPE_ID
		FOREIGN KEY (DEVICE_TYPE_ID)
			REFERENCES INFO_DEVICE_TYPE (ID)
);

CREATE INDEX INDX__INFO_DEV_PRT__DEV_TY_ID
	ON INFO_DEVICE_PART (DEVICE_TYPE_ID);