CREATE TABLE INFO_DEVICE_SPARE_TYPE --Тип Запчасти
(
	ID							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	ORDER_CODE					VARCHAR(50),
	NOMENCLATURE				VARCHAR(100) NOT NULL, 

	SHORT_NAME					VARCHAR(250) NOT NULL,
	FULL_NAME					VARCHAR(500) NOT NULL,

	DEVICE_TYPE_ID				INT NOT NULL,
	DEVICE_PART_ID				INT NOT NULL,
	DEVICE_MODEL_ID				INT, --Это может быть тип, относящийся к конкретной модели, или глобальный.
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATE_ID					INT NOT NULL,	
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
	CONSTRAINT FK_DEVICE_TYPE_ID
		FOREIGN KEY (DEVICE_TYPE_ID)
			REFERENCES INFO_DEVICE_TYPE (ID),
	CONSTRAINT FK_DEVICE_PART_ID
		FOREIGN KEY (DEVICE_PART_ID)
			REFERENCES INFO_DEVICE_PART (ID),
	CONSTRAINT FK_DEVICE_MODEL_ID
		FOREIGN KEY (DEVICE_MODEL_ID)
			REFERENCES INFO_DEVICE_MODEL (ID)
);

CREATE INDEX INDX__INFO_DEV_SPR_TYP__DEV_TY_ID
	ON INFO_DEVICE_SPARE_TYPE (DEVICE_TYPE_ID);