CREATE TABLE DOC_SERVICE_APPLICATION
(
    ID                      BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    
	DOC_NUMBER				VARCHAR(50) NOT NULL,
	DOC_DATE				DATE NOT NULL,
	BRANCH_ID				INT NOT NULL,

	DEVICE_TYPE_ID			INT,
	DEVICE_ID				INT NOT NULL,
	EXECUTOR_TYPE_ID		INT NOT NULL, --Исполнитель
	SERVICE_CONTRACTOR_ID	BIGINT, -- Если тип исполнителя — внешняя служба, этот параметр будет установлен автоматически из SERVICE_CONTRACTOR_ID таблицы DEVICE.
	RESPONSIBLE_PERSON_ID	BIGINT NOT NULL, -- Ответственный исполнитель
	PHONE_NUMBER			VARCHAR(50),

	PROCESS_DURATION		INT, -- Желаемое время решения (The front end is given a string, say 2:20 min. We convert it to minutes and store it, and when we give it to the front end, we return it in hour format)
	END_AT					TIMESTAMP WITHOUT TIME ZONE, --Время завершения работ

	APPLICATION_DESC		TEXT, --Краткое описание обращения
	PROBLEM_DESC			TEXT, --Комментарий, описание неисправности
	EXECUTOR_COMMENT		TEXT, --Комментарий исполнителя

	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	STATUS_ID				INT NOT NULL,

	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,

	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_DEVICE_ID
		FOREIGN KEY (DEVICE_ID)
			REFERENCES HL_DEVICE (ID),
	CONSTRAINT FK_EXECUTOR_TYPE_ID
		FOREIGN KEY (EXECUTOR_TYPE_ID)
			REFERENCES ENUM_EXECUTOR_TYPE (ID),
	CONSTRAINT FK_SERVICE_CONTRACTOR_ID
		FOREIGN KEY (SERVICE_CONTRACTOR_ID)
			REFERENCES INFO_CONTRACTOR (ID),
	CONSTRAINT FK_RESPONSIBLE_PERSON_ID
		FOREIGN KEY (RESPONSIBLE_PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_DEVICE_TYPE_ID
		FOREIGN KEY (DEVICE_TYPE_ID)
			REFERENCES INFO_DEVICE_TYPE (ID)
);

CREATE INDEX INDX__DOC_SER_APP__STID_DEVID
	ON DOC_SERVICE_APPLICATION (STATUS_ID , DEVICE_ID);