CREATE TABLE DOC_SERVICE_APPLICATION_SPARE
(
	ID                      BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID				BIGINT NOT NULL,
	DEVICE_SPARE_TYPE_ID	INT NOT NULL,
	QUANTITY				INT NOT NULL,
	
	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT    			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT NULL,
	MODIFIED_AT   			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   			INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_SERVICE_APPLICATION (ID) 
				ON DELETE CASCADE,
	CONSTRAINT FK_DEVICE_SPARE_TYPE_ID
		FOREIGN KEY (DEVICE_SPARE_TYPE_ID)
			REFERENCES INFO_DEVICE_SPARE_TYPE (ID)
);

CREATE INDEX INDX__DOC_SER_APP_SPR__OWNID
	ON DOC_SERVICE_APPLICATION_SPARE (OWNER_ID);