CREATE TABLE DOC_SPARE_MOVEMENT
(
	ID 						BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	DOC_NUMBER				VARCHAR(50) NOT NULL,
	DOC_DATE				DATE NOT NULL,
	
	MOVEMENT_TYPE_ID		INT NOT NULL,
	FROM_BRANCH_ID			INT,
	TO_BRANCH_ID			INT,
	FROM_USER_ID			INT,
	TO_USER_ID				INT,
	
	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	STATUS_ID				INT NOT NULL,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,
	
	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_MOVEMENT_TYPE_ID
		FOREIGN KEY (MOVEMENT_TYPE_ID)
			REFERENCES ENUM_MOVEMENT_TYPE (ID),
	CONSTRAINT FK_FROM_BRANCH_ID
		FOREIGN KEY (FROM_BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_TO_BRANCH_ID
		FOREIGN KEY (TO_BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_FROM_USER_ID
		FOREIGN KEY (FROM_USER_ID)
			REFERENCES SYS_USER (ID),
	CONSTRAINT FK_TO_USER_ID
		FOREIGN KEY (TO_USER_ID)
			REFERENCES SYS_USER (ID)
);