CREATE TABLE SYS_TABLE
(
	ID				INT NOT NULL PRIMARY KEY,
	SHORT_NAME 		VARCHAR(100) NOT NULL,
	FULL_NAME 		VARCHAR(200) NOT NULL,		
	DB_TABLE_NAME	VARCHAR(100) NOT NULL,
	CREATED_AT	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
)