CREATE TABLE ACC_PRESENT_SPARE_TURNOVER
(
	ID							UUID NOT NULL PRIMARY KEY,
	BRANCH_ID					INT NOT NULL,	
	USER_ID						INT,	
	DEVICE_SPARE_TYPE_ID		INT NOT NULL,
	QUANTITY					INT NOT NULL,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_USER_ID
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID),
	CONSTRAINT FK_DEVICE_SPARE_TYPE_ID
		FOREIGN KEY (DEVICE_SPARE_TYPE_ID)
			REFERENCES INFO_DEVICE_SPARE_TYPE (ID)
);

CREATE INDEX INDX__ACC_PRE_SPARE_TURNOVER__BRID_DEV_SP_TYPID
	 ON  ACC_PRESENT_SPARE_TURNOVER(BRANCH_ID , DEVICE_SPARE_TYPE_ID);