CREATE TABLE ACC_SPARE_TURNOVER
(
	ID							UUID NOT NULL PRIMARY KEY,

	DOC_NUMBER					VARCHAR(50) NOT NULL,
	DOC_DATE					DATE NOT NULL,
	PRESENT_SPARE_TURNOVER_ID	UUID NOT NULL,

	TABLE_ID					INT NOT NULL,
	DOCUMENT_ID					BIGINT NOT NULL,
	DOCUMENT_TABLE_ID			BIGINT,

	BRANCH_ID					INT NOT NULL,
	USER_ID						INT,	
	
	DEVICE_SPARE_TYPE_ID		INT NOT NULL,
	QUANTITY					INT NOT NULL,		
		
	IS_DEBIT					BOOLEAN NOT NULL,		

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_TABLE_ID
		FOREIGN KEY (TABLE_ID)
			REFERENCES SYS_TABLE (ID),
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_USER_ID
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID),
	CONSTRAINT FK_DEVICE_SPARE_TYPE_ID
		FOREIGN KEY (DEVICE_SPARE_TYPE_ID)
			REFERENCES INFO_DEVICE_SPARE_TYPE (ID),
	CONSTRAINT FK_PRESENT_SPARE_TURNOVER_ID
		FOREIGN KEY (PRESENT_SPARE_TURNOVER_ID)
			REFERENCES ACC_PRESENT_SPARE_TURNOVER (ID)
);

CREATE INDEX INDX__ACC_SPARE_TURNOVER__BRID_DEV_SP_TYPID
	 ON  ACC_SPARE_TURNOVER(BRANCH_ID , DEVICE_SPARE_TYPE_ID);