CREATE TABLE HL_NOTIFICATION
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	SUBJECT						VARCHAR(50) NOT NULL,
	MESSAGE						TEXT NOT NULL,
	NOTIFICATION_TEMPLATE_ID	INT NOT NULL, -- NOTIFICATION TEMPLATE lar ham bazaga saqlansa
	SENT_AT						TIMESTAMP WITHOUT TIME ZONE, -- NOTIFICATION yuborilgan vaqt
	USER_ID						INT NOT NULL, -- NOTIFICATION qabul qiluvchi userId
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	IS_READ						BOOL NOT NULL DEFAULT FALSE,
	READ_AT						TIMESTAMP WITHOUT TIME ZONE, -- NOTIFICATION o'qilgan vaqt
	STATE_ID					INT NOT NULL, -- IS_READ, IS_DELETE, IS_SEND
	
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_USER_ID
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID),

	CONSTRAINT FK_NOTIFICATION_TEMPLATE_ID
		FOREIGN KEY (NOTIFICATION_TEMPLATE_ID)
			REFERENCES ENUM_NOTIFICATION_TEMPLATE(ID),

	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE(ID)
);