version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_config:/etc/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
  rabbitmq_config:
  rabbitmq_logs: