## DEFAULT SETTINGS ARE NOT MEANT TO BE TAKEN STRAIGHT INTO PRODUCTION
## see https://www.rabbitmq.com/configure.html for further information
## on configuring RabbitMQ

## allow access to the guest user from anywhere on the network
## https://www.rabbitmq.com/access-control.html#loopback-users
## https://www.rabbitmq.com/production-checklist.html#users
loopback_users.guest = false

## Send all logs to stdout/TTY. Necessary to see logs when running via
## a containe

vm_memory_high_watermark.relative = 0.8 # memory threshold at which the flow control is triggered. default: 0.6
//..

# Logging
log.console = true # true to activate console logging, false to deactivate
log.console.level = warning # log levels: debug, info, warning, error, critical
log.console.formatter.level_format = uc # uc: full value, upper case, e.g. WARNING or INFO
log.console.formatter.plaintext.format = $time [$level] $pid $msg # ex: [WARNING] 2024-10-04 03:24:03.338466-04:00 Will reconcile virtual host processes on all cluster members...
log.console.formatter.single_line = off # recommended in production mode

log.file = rabbitmq.log # log file path or false to deactivate the file output
log.file.level = warning # log levels: debug, info, warning, error, critical
log.file.formatter.level_format = uc # uc: full value, upper case, e.g. WARNING or INFO
log.file.formatter.plaintext.format = $time [$level] $pid $msg # ex: [WARNING] 2024-10-04 03:24:03.338466-04:00 Will reconcile virtual host processes on all cluster members...
log.file.formatter.single_line = off # recommended in production mode

# ---> choose: log.file.rotation.date cannot be combined with log.file.rotation.size
# --> date
log.file.rotation.date = $D0 # rotate every night at midnight
log.file.rotation.count = 7 # keep up to 7 archived log files in addition to the current one
log.file.rotation.compress = true # archived log files will be compressed
# --> size
log.file.rotation.size = 104857600 # rotate when the file reaches 100 MiB
log.file.rotation.count = 10 # keep up to 10 archived log files in addition to the current one
log.file.rotation.compress = true # archived log files will be compressed
# <---