CREATE TABLE INFO_CONTRACTOR
(
 	ID          	BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

 	SHORT_NAME   	VARCHAR(250) NOT NULL,
 	FULL_NAME    	VARCHAR(250) NOT NULL,

 	COUNTRY_ID   	INT NOT NULL,
 	REGION_ID    	INT NOT NULL,
 	DISTRICT_ID  	INT NOT NULL,
 	BANK_ID      	INT NOT NULL,
 	ADDRESS     	VARCHAR(500) NULL,
 	PHONE_NUMBER 	VARCHAR(15) NULL,
 	CONTACT_INFO 	VARCHAR(250) NULL,
 	
	INN         	VARCHAR(9) NOT NULL,
 	ACCOUNTER   	VARCHAR(250) NULL,
 	DIRECTOR    	VARCHAR(250) NULL,
 	VAT_CODE     	VARCHAR(30) NULL,
    STATE_ID        INT NOT NULL,

	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	

    CONSTRAINT FK_STATE_ID
		 FOREIGN KEY ( STATE_ID )
		 	 REFERENCES ENUM_STATE ( ID ),
 	CONSTRAINT FK_COUNTRY_ID
		 FOREIGN KEY ( COUNTRY_ID )
		 	 REFERENCES INFO_COUNTRY ( ID ),
 	CONSTRAINT FK_REGION_ID 
		FOREIGN KEY ( REGION_ID ) 
			REFERENCES INFO_REGION ( ID ),
 	CONSTRAINT FK_DISTRICT_ID 
		FOREIGN KEY ( DISTRICT_ID ) 
			REFERENCES INFO_DISTRICT ( ID ),
 	CONSTRAINT FK_BANK_ID 
		FOREIGN KEY ( BANK_ID )
			 REFERENCES INFO_BANK ( ID )
);