CREATE TABLE DOC_TRANSPORT_SETTING_INSURANCE -- Страховка
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	INSURANCE_TYPE_ID			INT NOT NULL,
	INS_NUMBER					VARCHAR(50) NOT NULL,		--№ страхового полиса
	EXPIRE_AT					DATE NOT NULL,		--Срок действия
	
	CONTRACTOR_ID				BIGINT NOT NULL,
	RESPONSIBLE_PERSON_ID		BIGINT NOT NULL,	--Ответственный за страхование

	DETAILS						TEXT,
	NOTIFY_BEFORE_DAY			INT NOT NULL, --За сколько дней оповестить ответственного

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_RESPONSIBLE_PERSON_ID
		FOREIGN KEY (RESPONSIBLE_PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_INSURANCE_TYPE_ID
		FOREIGN KEY (INSURANCE_TYPE_ID)
			REFERENCES INFO_INSURANCE_TYPE (ID),
	CONSTRAINT FK_CONTRACTOR_ID
		FOREIGN KEY (CONTRACTOR_ID)
			REFERENCES INFO_CONTRACTOR (ID)
);

CREATE UNIQUE INDEX UINDX__DOC_TR_SET_INSURANCE_OWNID_ISDEL
	ON DOC_TRANSPORT_SETTING_INSURANCE (OWNER_ID,IS_DELETED)
		WHERE IS_DELETED = FALSE;
