CREATE TABLE HL_TRANSPORT_FILE
(
    ID                          UUID NOT NULL PRIMARY KEY,
    OWNER_ID                    INT NOT NULL,
    FILE_NAME                   VARCHAR(250) NOT NULL, 

	IS_DELETED				    BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

    CONSTRAINT FK_OWNER_ID 
        FOREIGN KEY (OWNER_ID)
            REFERENCES HL_TRANSPORT(ID)
                ON DELETE CASCADE
);

CREATE INDEX INDX__HL_TRNSPRT__OWNID
    ON HL_TRANSPORT(OWNER_ID);