CREATE TABLE ENUM_NOTIFICATION_TEMPLATE
(
	ID 							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	KEY							VARCHAR(50) NOT NULL, -- 
	SUBJECT						VARCHAR(100) NOT NULL,
	MESSAGE						TEXT NOT NULL,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATE_ID					INT NOT NULL,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,

	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE(ID)
);