CREATE TABLE DOC_NOTIFICATION_TEMPLATE_SETTING_USER (
  ID                      	BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

  OWNER_ID          		BIGINT NOT NULL,
  USER_ID                  	INT NOT NULL,

  IS_DELETED              	BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT              	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY              	INT,
  MODIFIED_AT              TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY              INT,

  CONSTRAINT FK_DOC_NOTIFICATION_TEMPLATE_SETTING_ID
    FOREIGN KEY (OWNER_ID)
      REFERENCES DOC_NOTIFICATION_TEMPLATE_SETTING(ID)
      	ON DELETE CASCADE,

  CONSTRAINT FK_USER_ID
    FOREIGN KEY (USER_ID)
      REFERENCES SYS_USER(ID),

  CONSTRAINT UQ_TEMPLATE_USER
    UNIQUE(OWNER_ID, USER_ID)
);