CREATE TABLE HL_BRANCH
(
 	ID              INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

	UNIQUE_CODE		VARCHAR(50) NOT NULL, -- e.g  11346
 	PARENT_ID       INT NULL,
	
 	SHORT_NAME      VARCHAR(250) NOT NULL,
 	FULL_NAME       VARCHAR(250) NOT NULL,

 	ORGANIZATION_ID INT NOT NULL,
 	COUNTRY_ID      INT NOT NULL,
	REGION_ID       INT NOT NULL,
 	DISTRICT_ID     INT NOT NULL,
 	ADDRESS        	VARCHAR(500) NOT NULL,
	LATITUDE		VARCHAR(50),
	LONGITUDE		VARCHAR(50),
 	
 	STATE_ID        INT NOT NULL,
	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT    	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT NULL,
	MODIFIED_AT   	TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   	INT,

 	CONSTRAINT FK_PARENT_ID
		FOREIGN KEY ( PARENT_ID ) 
			REFERENCES HL_BRANCH ( ID ),
	CONSTRAINT FK_COUNTRY_ID
		 FOREIGN KEY ( COUNTRY_ID )
		 	 REFERENCES INFO_COUNTRY ( ID ),
 	CONSTRAINT FK_REGION_ID 
		FOREIGN KEY ( REGION_ID ) 
			REFERENCES INFO_REGION ( ID ),
 	CONSTRAINT FK_DISTRICT_ID 
		FOREIGN KEY ( DISTRICT_ID ) 
			REFERENCES INFO_DISTRICT ( ID )
);
