CREATE TABLE SYS_USER
(
	ID					INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

	USER_NAME			VARCHAR(250) NOT NULL,
	USER_IDENTITY		VARCHAR(250),
	
	PASSWORD_HASH		VARCHAR(250) NOT NULL,
	PASSWORD_SALT		VARCHAR(259) NOT NULL,
	TEMPORARY_INFO		VARCHAR(500), -- For saving password encrypted format untill SSO integration.After integration we will delete info or maybe will drop column totally.It is practically wrong but is temporary solution because of short time limit

	ORGANIZATION_ID		INT NOT NULL,
	BRANCH_ID			INT,
	DEPARTMENT_ID		INT,
	POSITION_ID			INT,
	PERSON_ID			BIGINT NOT NULL,
	PHONE_NUMBER		VARCHAR(50),
	
	LANGUAGE_ID			INT,
	LAST_ACCESS_TIME	TIMESTAMP WITHOUT TIME ZONE,
	
	IS_DELETED			BOOL NOT NULL DEFAULT FALSE,	
	STATE_ID			INT NOT NULL,
	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_ORGANIZATION_ID
		FOREIGN KEY (ORGANIZATION_ID) 
			REFERENCES INFO_ORGANIZATION (ID),
	CONSTRAINT FK_PERSON_ID
		FOREIGN KEY (PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_LANGUAGE_ID
		FOREIGN KEY (LANGUAGE_ID)
			REFERENCES ENUM_LANGUAGE (ID),
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_POSITION_ID
		FOREIGN KEY (POSITION_ID)
			REFERENCES HL_POSITION(ID)	
);

CREATE INDEX SYS_USER_INDEX_ISDEL_ORGID__STAID
	ON SYS_USER (IS_DELETED, ORGANIZATION_ID , STATE_ID);

CREATE UNIQUE INDEX SYS_USER_INDEX_USER_NAME
	ON SYS_USER(USER_NAME);