CREATE TABLE QR.DOC_MACHINE_READABLE_CODE_SETTING
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	
	DOC_NUMBER					VARCHAR(50) NOT NULL,
	DOC_DATE					DATE NOT NULL,
	
	NAME						VARCHAR(50) NOT NULL,
	CODE_FORM_TYPE_ID			INT,
	CODE_TYPE_ID			    INT NOT NULL, -- ATM,CASSETTE,COLLECTOR,SET OF KEY...

	HAS_PREFEX					BOOL NOT NULL,
	IS_UUID						BOOL NOT NULL,

	PREFEX						VARCHAR(10),
	NEXT_TEMPLATE_LENGTH		INT,
	NEXT_TEMPLATE_LETTER_COUNT	INT, -- PREFEXDAN KEYINGI TEMPLATE NECHTA XARF MAVJUD
	NEXT_TEMPLATE_NUMBER_COUNT	INT, -- PREFEXDAN KEYINGI TEMPLATE NECHTA SON MAVJUD
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,	
	STATUS_ID					INT NOT NULL,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_QODETYPEID
		FOREIGN KEY (CODE_TYPE_ID)
			REFERENCES QR.ENUM_QR_CODE_TYPE (ID),
	CONSTRAINT FK_STATUSID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_CODE_FORM_TYPE_ID
		FOREIGN KEY (CODE_FORM_TYPE_ID)
			REFERENCES QR.ENUM_CODE_FORM_TYPE (ID)
);