CREATE TABLE ENUM_BASE_DEVICE_TYPE --Базовый тип устройств (Устройства самообслуживания / Автомобили / Кассовая техника)
(
    ID 			INT NOT NULL PRIMARY KEY,
    ORDER_CODE 	VARCHAR(50),
    SHORT_NAME 	VARCHAR(250) NOT NULL,
    FULL_NAME  	VARCHAR(300) NOT NULL,

	IS_DELETED	BOOL NOT NULL DEFAULT FALSE,	
    CREATED_AT 	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);