CREATE TABLE DOC_SERVICE_APPLICATION_PART
(
	ID                      BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID				BIGINT NOT NULL,
	DEVICE_PART_ID			INT NOT NULL,
	APPLICATION_PURPOSE_ID	INT NOT NULL,
	SERVICE_TYPE_ID			INT,
	
	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT    			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT NULL,
	MODIFIED_AT   			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   			INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_SERVICE_APPLICATION (ID) 
				ON DELETE CASCADE,
	CONSTRAINT FK_DEVICE_PART_ID
		FOREIGN KEY (DEVICE_PART_ID)
			REFERENCES INFO_DEVICE_PART (ID) ,
	CONSTRAINT FK_APPLICATION_PURPOSE_ID
		FOREIGN KEY (APPLICATION_PURPOSE_ID)
			REFERENCES ENUM_APPLICATION_PURPOSE (ID),
	CONSTRAINT FK_SERVICE_TYPE_ID
		FOREIGN KEY (SERVICE_TYPE_ID)
			REFERENCES INFO_SERVICE_TYPE (ID)
);

CREATE INDEX INDX__DOC_SER_APP_PRT__OWNID
	ON DOC_SERVICE_APPLICATION_PART (OWNER_ID);