CREATE TABLE DOC_SERVICE_APPLICATION_EXECUTOR_FILE
(
    ID                          UUID NOT NULL PRIMARY KEY,
    OWNER_ID                    BIGINT NOT NULL,
    FILE_NAME                   VARCHAR(250) NOT NULL, 

	IS_DELETED				    BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

    CONSTRAINT FK_OWNER_ID 
        FOREIGN KEY (OWNER_ID)
            REFERENCES DOC_SERVICE_APPLICATION(ID)
                ON DELETE CASCADE
);

CREATE INDEX INDX__DOC_SER_APP_EXTR_FIL__OWNID
    ON DOC_SERVICE_APPLICATION_EXECUTOR_FILE(OWNER_ID);