CREATE TABLE DOC_SPARE_MOVEMENT_TABLE
(
	ID 						BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID				BIGINT NOT NULL,
	DEVICE_SPARE_TYPE_ID	INT NOT NULL,
	QUANTITY				INT NOT NULL,

	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,

	CONSTRAINT FK_OWNER_ID 
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_SPARE_MOVEMENT (ID) ON DELETE CASCADE,
	CONSTRAINT FK_DEVICE_SPARE_TYPE_ID
		FOREIGN KEY (DEVICE_SPARE_TYPE_ID)
			REFERENCES INFO_DEVICE_SPARE_TYPE (ID)
);

CREATE INDEX INDX__DOC_SP_MOV_TAB__OWNID
	ON DOC_SPARE_MOVEMENT_TABLE (OWNER_ID);