INSERT INTO SYS_PERMISSION_GROUP 
(ID, SHORT_NAME, FULL_NAME) VALUES 
(1,N'Док',N'Документы');
INSERT INTO SYS_PERMISSION_GROUP 
(ID, SHORT_NAME, FULL_NAME) VALUES 
(2,N'Спр','Справочники');
INSERT INTO SYS_PERMISSION_GROUP 
(ID, SHORT_NAME, FULL_NAME) VALUES 
(3,N'Сис','Системные');
INSERT INTO SYS_PERMISSION_GROUP 
(ID, SHORT_NAME, FULL_NAME) VALUES 
(4,N'Отч','Отчеты');
