CREATE TABLE QR.ENUM_CODE_FORM_TYPE (
  ID                INT NOT NULL PRIMARY KEY,

  ORDER_CODE		VARCHAR(50),  
  SHORT_NAME        VARCHAR(250) NOT NULL,
  FULL_NAME         VARCHAR(500) NOT NULL,  

  
  IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
  STATE_ID			INT NOT NULL,
  CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,

  CONSTRAINT FK_STATE_ID
  	FOREIGN KEY (STATE_ID)
  		REFERENCES ENUM_STATE(id) 
);