CREATE TABLE ENUM_TRANSPORT_TYPE
(
	ID				INT NOT NULL PRIMARY KEY,
	ORDER_CODE		VARCHAR(5),
	
	SHORT_NAME		VARCHAR(250) NOT NULL,
	FULL_NAME		VARCHAR(250) NOT NULL,
	
	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	STATE_ID		INT NOT NULL,	  
 	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);