CREATE TABLE INFO_TRANSPORT_MODEL -- DAMAS,MINEVEN,TRACKER,MAN, HOVO,...
(
	ID							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	ORDER_CODE					VARCHAR(50),
	
	SHORT_NAME					VARCHAR(250) NOT NULL,
	FULL_NAME					VARCHAR(500) NOT NULL,
	TRANSPORT_TYPE_ID			INT NOT NULL,
	TRANSPORT_BRAND_ID			INT NOT NULL,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,	
	STATE_ID					INT NOT NULL,	
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (id),	
	CONSTRAINT FK_TRANSPORT_TYPE_ID
		FOREIGN KEY (TRANSPORT_TYPE_ID)
			REFERENCES ENUM_TRANSPORT_TYPE (id),
	CONSTRAINT FK_TRANSPORT_BRAND_ID
		FOREIGN KEY (TRANSPORT_BRAND_ID)
			REFERENCES INFO_TRANSPORT_BRAND (id)
);