CREATE TABLE HL_TRANSPORT
(
	ID							INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
		
	ORDER_CODE					VARCHAR(50),
	BRANCH_ID					INT NOT NULL,
	DEPARTMENT_ID				INT,

	UNIQUE_CODE					UUID NOT NULL,

	TRANSPORT_MODEL_ID			INT NOT NULL,
	TRANSPORT_USE_TYPE_ID		INT NOT NULL,
	TRANSPORT_BRAND_ID			INT NOT NULL,
	TRANSPORT_COLOR_ID			INT NOT NULL,
	
	MANUFACTURED_AT				DATE NOT NULL, -- Год выпуска
	PURCHASED_AT				DATE NOT NULL, -- Дата приобретения

	STATE_CODE					VARCHAR(5) NOT NULL, --01,80,70  -- Avtomat tushirilishi ham mumkin region asosida yoki region dagi state_code bo'lmasa demak alohida qo'lda kiritish ham mumkin bo'ladi
	STATE_NUMBER				VARCHAR(50) NOT NULL, --AD567RG -- nega ikkiga ajratilgan frontda ko'rsatishga oson bo'lishi uchun ham ikkiga bo'lib chiroyli qilib ko'rsatadi
	VIN_NUMBER					VARCHAR(50) NOT NULL, --Kuzov raqami
		
	PURCHASED_AMOUNT			NUMERIC(18,2) NOT NULL, -- Стоимость приобретения
	AMORTIZATION_PERIOD			INT NOT NULL, -- Срок аммортизации
	QR_CODE_REGISTRY_ID			UUID, -- Har bir mashina uchun QR code shakllanadi avtomat create vaqtida


	STATE_ID					INT NOT NULL,
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
  	CREATED_AT    				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT NULL,
	MODIFIED_AT   				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   				INT,	
		
	CONSTRAINT FK_TRANSPORT_MODEL_ID
		FOREIGN KEY (TRANSPORT_MODEL_ID)
			REFERENCES INFO_TRANSPORT_MODEL (id),
	CONSTRAINT FK_TRANSPORT_USE_TYPE_ID
		FOREIGN KEY (TRANSPORT_USE_TYPE_ID)
			REFERENCES INFO_TRANSPORT_USE_TYPE (id),
	CONSTRAINT FK_TRANSPORT_BRAND_ID
		FOREIGN KEY (TRANSPORT_BRAND_ID)
			REFERENCES INFO_TRANSPORT_BRAND (id),	
	CONSTRAINT FK_TRANSPORT_COLOR_ID
		FOREIGN KEY (TRANSPORT_COLOR_ID)
			REFERENCES INFO_TRANSPORT_COLOR (id),	
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (id),	
	CONSTRAINT FK_DEPARTMENT_ID
		FOREIGN KEY (DEPARTMENT_ID)
			REFERENCES HL_DEPARTMENT (id),
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (id),
	CONSTRAINT FK_QR_CODE_REGISTRY_ID
		FOREIGN KEY (QR_CODE_REGISTRY_ID)
			REFERENCES QR.SYS_QR_CODE_REGISTRY (id)
);

CREATE INDEX INDX__HL_TRPRT_ISDEL_STID_BRID
	ON HL_TRANSPORT(IS_DELETED,STATE_ID,BRANCH_ID);

CREATE UNIQUE INDEX IDX_VIN_STATE_ACTIVE 
ON HL_TRANSPORT(VIN_NUMBER) 
WHERE STATE_ID = 1;