CREATE TABLE HL_DRIVER_DOCUMENT
(
	--Prava
	--Sug'urta
	--....	
	ID						BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

	OWNER_ID				INT NOT NULL,

	DOCUMENT_TYPE_ID		INT NOT NULL,
	DOCUMENT_NUMBER			VARCHAR(50) NOT NULL,
	DOCUMENT_START_ON		TIMESTAMP WITHOUT TIME ZONE,
	DOCUMENT_END_ON			TIMESTAMP WITHOUT TIME ZONE,
	DOCUMENT_FILE_ID		UUID,--Bu bir nechta bo'lsa table qismiga tushirish kerak buni ham
	DOCUMENT_FILE_NAME      VARCHAR(250),

	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,	
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES HL_DRIVER (ID)
);

CREATE INDEX INDX_HL_DRIVER_DOCUMENT_OWN_ID
	ON HL_DRIVER_DOCUMENT (OWNER_ID);