CREATE TABLE HL_PRESENT_TRACKING_INFO (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    PERSON_ID       BIGINT NOT NULL,
    LATITUDE        NUMERIC(18,6) NOT NULL,
    LONGITUDE       NUMERIC(18,6) NOT NULL,
    CREATED_AT      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATED_BY      INT,    

    CONSTRAINT FK_HL_PRESENT_TRACKING_INFO_PERSON
        FOREIGN KEY (PERSON_ID)
        REFERENCES HL_PERSON (ID) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION delete_old_location()
RETURNS TRIGGER AS $$
BEGIN
    -- Agar eski yozuv bo'lsa, uni o'chirish
    DELETE FROM HL_PRESENT_TRACKING_INFO WHERE PERSON_ID = NEW.PERSON_ID;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delete_old_location
BEFORE INSERT ON HL_PRESENT_TRACKING_INFO
FOR EACH ROW EXECUTE FUNCTION delete_old_location();