CREATE TABLE DOC_TRANSPORT_SETTING
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

	DOC_NUMBER					VARCHAR(50) NOT NULL,
	DOC_DATE					DATE NOT NULL, -- Дата закрепления

	TRANSPORT_ID				INT NOT NULL,
	DRIVER_ID					INT NOT NULL, -- ФИО водителя ID bilan bo'g'lanadi
	
	LICENSE_NUMBER				VARCHAR(50) NOT NULL, -- Номер водительского удост
	LICENSE_END_AT				DATE NOT NULL, -- Срок действия ВУ

	POA_NUMBER					VARCHAR(50) NOT NULL,	-- POA - POWER OF ATTORNEY -  № доверенности
	POA_END_AT					DATE NOT NULL, --Срок действия доверенности
	
	MED_CERT_NUMBER				VARCHAR(50) NOT NULL, -- № медицинской справки
	MED_CERT_END_AT				DATE NOT NULL, -- Срок действия справки

	MANAGER_FULL_NAME			VARCHAR(250), -- Bu balki id orqali bog'lanishi mumkin Person table ga kerakmi o'zi ?

	----
	LOAD_CAPACITY				NUMERIC(18,2) NOT NULL, --Грузопushодъемность
	SEAT_COUNT					INT NOT NULL, -- Количество посадочных мест
	ODOMETR_INDICATOR			NUMERIC(18,2) NOT NULL, -- Значение одометра на дату
	FUEL_CARD_NUMBER			VARCHAR(50) NOT NULL, --№ топливной карты
	RESPONSIBLE_PERSON_ID		BIGINT NOT NULL, -- Ответственный за сопровождение транспорта
	
	----
	MESSAGE						TEXT,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATUS_ID					INT NOT NULL,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_TRANSPORT_ID
		FOREIGN KEY (TRANSPORT_ID)
			REFERENCES HL_TRANSPORT (ID),
	CONSTRAINT FK_RESPONSIBLE_PERSON_ID
		FOREIGN KEY (RESPONSIBLE_PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_DRIVER_ID
		FOREIGN KEY (DRIVER_ID)
			REFERENCES HL_DRIVER (ID)
);


CREATE INDEX INDX_DOC_TR_SETT_TRID_STID
	ON DOC_TRANSPORT_SETTING (TRANSPORT_ID , STATUS_ID);