CREATE TABLE DOC_TRANSPORT_SETTING_TIRE -- Количество закрепленных шин
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,
	QUANTITY					INT NOT NULL, --количество
	SIZE						VARCHAR(50) NOT NULL, --Размер
	PRODUCED_AT					DATE NOT NULL, --Дата
	MILE_AGE					NUMERIC(18,2) NOT NULL, --Пробег

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID)
);

CREATE INDEX INDX_DOC_TRANSPORT_SETTING_TIRE_OWN_ID
	ON DOC_TRANSPORT_SETTING_TIRE (OWNER_ID);