CREATE TABLE DOC_TRANSPORT_SETTING_FUEL -- топлива
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	FUEL_TYPE_ID				INT NOT NULL, --ТИП
	TANK_VOLUME					NUMERIC(18,2) NOT NULL, --Объем бака
	MONTHLY_LIMIT				NUMERIC(18,2) NOT NULL, --Лимит на месяц
	REMAINING					NUMERIC(18,2) NOT NULL DEFAULT 0, --Остаток на момент заведения

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID),
	CONSTRAINT FK_FUEL_TYPE_ID
		FOREIGN KEY (FUEL_TYPE_ID)
			REFERENCES INFO_FUEL_TYPE (ID)
);

CREATE INDEX INDX__DOC_TR_SET_FUEL_OWN_ID
	ON DOC_TRANSPORT_SETTING_FUEL (OWNER_ID);

CREATE UNIQUE INDEX UINDX__DOC_TR_SET_FUEL_OWNID_ISDEL_FUTYPEID
	ON DOC_TRANSPORT_SETTING_FUEL (OWNER_ID,IS_DELETED,FUEL_TYPE_ID)
		WHERE IS_DELETED = FALSE;