CREATE TABLE DOC_TRANSPORT_SETTING_LIQUID -- Стеклоомывающая жидкость
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	--LIQUID_TYPE_ID				INT NOT NULL, --Тип теклоомывающая жидкость  -- Bu kerakmi odatda oddiy suv bo'ladi ?
	TANK_VOLUME					NUMERIC(18,2) NOT NULL, --Объем в двигателе
	MONTHLY_LIMIT				NUMERIC(18,2) NOT NULL, --Лимит на месяц
	REMAINING					NUMERIC(18,2) NOT NULL DEFAULT 0, --Остаток на момент заведения

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID)
);

CREATE INDEX INDX_DOC_TRANSPORT_SETTING_LIQUID_OWN_ID
	ON DOC_TRANSPORT_SETTING_LIQUID (OWNER_ID);

CREATE UNIQUE INDEX UINDX__DOC_TR_SET_LIQ_OWNID_ISDEL
	ON DOC_TRANSPORT_SETTING_LIQUID (OWNER_ID,IS_DELETED)
		WHERE IS_DELETED = FALSE;