CREATE TABLE DOC_EXPENSE --расходы
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

	DOC_NUMBER					VARCHAR(50) NOT NULL,
	DOC_DATE					DATE NOT NULL, -- Дата расходы

	BRANCH_ID					INT NOT NULL,
	TRANSPORT_ID				INT NOT NULL,
	DRIVER_ID					INT NOT NULL, -- ФИО водителя ID bilan bo'g'lanadi
	EXPENSE_TYPE_ID				INT NOT NULL, --Тип затрат
	PRICE						NUMERIC(18,5) NOT NULL,

	CONTRACTOR_ID				BIGINT,
	CONTRACTOR_NAME				VARCHAR(250),
	
	MESSAGE						TEXT,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATUS_ID					INT NOT NULL,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_TRANSPORT_ID
		FOREIGN KEY (TRANSPORT_ID)
			REFERENCES HL_TRANSPORT (ID),
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_DRIVER_ID
		FOREIGN KEY (DRIVER_ID)
			REFERENCES HL_DRIVER (ID),
	CONSTRAINT FK_EXPENSE_TYPE_ID
		FOREIGN KEY (EXPENSE_TYPE_ID)
			REFERENCES ENUM_EXPENSE_TYPE (ID),
	CONSTRAINT FK_CONTRACTOR_ID
		FOREIGN KEY (CONTRACTOR_ID)
			REFERENCES INFO_CONTRACTOR (ID)
);

CREATE INDEX INDX__DOC_EXPENSE__DRVRID_STTSID
	ON DOC_EXPENSE (DRIVER_ID,STATUS_ID);

CREATE INDEX INDX__DOC_EXPENSE__TRID_STID
	ON DOC_EXPENSE (TRANSPORT_ID , STATUS_ID);