CREATE TABLE DOC_REFUEL --заправку
(
    ID                      BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    
	DOC_NUMBER				VARCHAR(50) NOT NULL,
	DOC_DATE				DATE NOT NULL, -- Дата заправку
	
	BRANCH_ID				INT NOT NULL,
    FUEL_CARD_ID  			INT NOT NULL,        
	TRANSPORT_ID			INT NOT NULL,
	DRIVER_ID				INT NOT NULL,
    FUEL_TYPE_ID            INT NOT NULL,

    LITRE                   NUMERIC(18,2) NOT NULL,
	LITRE_PRICE				NUMERIC(18,2) NOT NULL DEFAULT 0,
    CHEQUE_NUMBER           VARCHAR(50) NOT NULL,
    ADDRESS                 VARCHAR(500) NOT NULL,

	MESSAGE					TEXT,

	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	STATUS_ID				INT NOT NULL,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,

	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID),
	CONSTRAINT FK_TRANSPORT_ID
		FOREIGN KEY (TRANSPORT_ID)
			REFERENCES HL_TRANSPORT (ID),
	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_DRIVER_ID
		FOREIGN KEY (DRIVER_ID)
			REFERENCES HL_DRIVER (ID),
	CONSTRAINT FK_FUEL_TYPE_ID
		FOREIGN KEY (FUEL_TYPE_ID)
			REFERENCES INFO_FUEL_TYPE (ID),
	CONSTRAINT FK_FUEL_CARD_ID
		FOREIGN KEY (FUEL_CARD_ID)
			REFERENCES HL_FUEL_CARD (ID)
);

CREATE INDEX INDX__DOC_REFUEL__DRVRID_STTSID
	ON DOC_REFUEL (DRIVER_ID,STATUS_ID);

CREATE INDEX INDX__DOC_REFUEL__TRID_STID
	ON DOC_REFUEL (TRANSPORT_ID , STATUS_ID);