INSERT INTO public.HL_NUMBER_TEMPLATE(DATE, DOCUMENT, TEMPLATE, ORGANIZATION_ID, CREATED_AT) VALUES
('2025-03-15',N'DOC_REFUEL',N'RFL-{branch}-{shortfinanceyear}-{nextnumber}',1,'2025-03-15');

INSERT INTO public.HL_NUMBER_TEMPLATE(DATE, DOCUMENT, TEMPLATE, ORGANIZATION_ID, CREATED_AT) VALUES
('2025-04-04',N'DOC_EXPENSE',N'EXP-{branch}-{shortfinanceyear}-{nextnumber}',1,'2025-04-04');

INSERT INTO public.HL_NUMBER_TEMPLATE(DATE, DOCUMENT, TEMPLATE, ORGANIZATION_ID, CREATED_AT) VALUES
('2025-04-04',N'DOC_NOTIFICATION_TEMPLATE_SETTING',N'NTS-{branch}-{shortfinanceyear}-{nextnumber}',1,'2025-04-30');