CREATE TABLE INFO_TIRE_SIZE -- Shina o‘lchamlari
(
	ID							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	ORDER_CODE					VARCHAR(50),

	WIDTH						NUMERIC(18,2) NOT NULL, 
	HEIGHT						NUMERIC(18,2) NOT NULL,  
	RADIUS						NUMERIC(18,2) NOT NULL,  

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	STATE_ID					INT NOT NULL,	
	
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (id)
);
