CREATE TABLE HL_PRESENT_NOTIFICATION
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

	OWNER_ID					BIGINT NOT NULL,
	SUBJECT						VARCHAR(100) NOT NULL,
	MESSAGE						TEXT NOT NULL,
	NOTIFICATION_TEMPLATE_ID	INT NOT NULL, -- NOTIFICATION TEMPLATE lar ham bazaga saqlansa
	SEND_AT						TIMESTAMP WITHOUT TIME ZONE, -- NOTIFICATION yuborilishi kerak bo'lgan vaqt
	USER_ID						INT NOT NULL, -- NOTIFICATION qabul qiluvchi userId
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_USER_ID
		FOREIGN KEY (USER_ID)
			REFERENCES SYS_USER (ID),
			
	CONSTRAINT FK_NOTIFICATION_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES HL_NOTIFICATION (ID),

	CONSTRAINT FK_NOTIFICATION_TEMPLATE_ID
		FOREIGN KEY (NOTIFICATION_TEMPLATE_ID)
			REFERENCES ENUM_NOTIFICATION_TEMPLATE(ID)
);