CREATE OR REPLACE FUNCTION public.get_total_expense(
	p_branch_id integer,
	p_transport_id integer,
	p_driver_id integer,
	p_from_date timestamp without time zone,
	p_to_date timestamp without time zone)
RETURNS TABLE(
	TRANSPORT_ID integer,
	DRIVER_ID integer,
	BRANCH_ID integer,
	BRANCH_NAME VARCHAR(250),
	TRANSPORT_INFO VARCHAR(500),
	DRIVER VARCHAR(300), 
	TOTAL_SUM numeric
)AS $$
BEGIN
RETURN QUERY
	WITH EXPENSE_PRICES_SUM AS(
		SELECT 
			E.TRANSPORT_ID AS TRANSPORT_ID,
			E.DRIVER_ID AS DRIVER_ID,
			COALESCE(SUM(EB.PRICE), 0) +
		    COALESCE(SUM(EIP.PRICE), 0) +
		    COALESCE(SUM(EIU.PRICE), 0) +
		    COALESCE(SUM(ET.PRICE), 0) +
		    COALESCE(SUM(EL.PRICE), 0) +
		    COALESCE(SUM(EO.PRICE), 0) AS TOTAL_EXPENSE_SUM
		
		FROM DOC_EXPENSE AS E
		LEFT JOIN DOC_EXPENSE_BATTERY AS EB ON E.ID = EB.OWNER_ID
		LEFT JOIN DOC_EXPENSE_INSPECTION AS EIP ON E.ID = EIP.OWNER_ID
		LEFT JOIN DOC_EXPENSE_INSURANCE AS EIU ON E.ID = EIU.OWNER_ID
		LEFT JOIN DOC_EXPENSE_TIRE AS ET ON E.ID = ET.OWNER_ID
		LEFT JOIN DOC_EXPENSE_LIQUID AS EL ON E.ID = EL.OWNER_ID
		LEFT JOIN DOC_EXPENSE_OIL AS EO ON E.ID = EO.OWNER_ID
		WHERE E.STATUS_ID = 3 AND
			(E.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
			(E.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
			(E.DRIVER_ID = p_driver_id OR p_driver_id IS NULL) AND
			(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND (p_to_date IS NULL OR p_to_date >= E.MODIFIED_AT)
		GROUP BY E.TRANSPORT_ID, E.DRIVER_ID
	), REFUEL_PRICES_SUM AS(
		SELECT
			R.TRANSPORT_ID,
			R.DRIVER_ID,
			COALESCE(SUM(R.LITRE * R.LITRE_PRICE), 0) AS TOTAL_REFUEL_SUM
		FROM DOC_REFUEL AS R
		WHERE R.STATUS_ID = 3 AND
			(R.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
			(R.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
			(R.DRIVER_ID = p_driver_id OR p_driver_id IS NULL) AND
			(R.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND (p_to_date >= R.MODIFIED_AT OR p_to_date IS NULL)
		GROUP BY R.TRANSPORT_ID, R.DRIVER_ID
	), GENERAL_EXPENSES AS(
		SELECT 
		    COALESCE(EPS.TRANSPORT_ID, RPS.TRANSPORT_ID) AS TRANSPORT_ID,
		    COALESCE(EPS.DRIVER_ID, RPS.DRIVER_ID) AS DRIVER_ID,
		    COALESCE(EPS.TOTAL_EXPENSE_SUM, 0) + COALESCE(RPS.TOTAL_REFUEL_SUM, 0) AS TOTAL_SUM
		FROM EXPENSE_PRICES_SUM EPS
		FULL OUTER JOIN REFUEL_PRICES_SUM RPS 
		    ON EPS.TRANSPORT_ID = RPS.TRANSPORT_ID AND EPS.DRIVER_ID = RPS.DRIVER_ID
	)
	
	SELECT
		TS.transport_id,
		TS.driver_id,
		TS.branch_id,
		B.full_name AS BRANCH_NAME,
		CAST(T.STATE_CODE || ' ' || T.STATE_NUMBER || ' (' || TM.FULL_NAME || ')' AS VARCHAR) AS TRANSPORT_INFO,
		P.FULL_NAME AS DRIVER,
		SUM(GE.TOTAL_SUM) AS TOTAL_SUM
	FROM DOC_TRANSPORT_SETTING AS TS
	JOIN HL_TRANSPORT AS T ON TS.transport_id = T.id
	JOIN INFO_TRANSPORT_MODEL AS TM ON T.transport_model_id = TM.id
	JOIN HL_DRIVER AS D ON TS.driver_id = D.id
	JOIN HL_PERSON AS P ON D.person_id = P.id
	LEFT JOIN HL_BRANCH AS B ON TS.branch_id = B.id
	JOIN GENERAL_EXPENSES AS GE ON TS.transport_id = GE.TRANSPORT_ID AND TS.driver_id = GE.DRIVER_ID
	WHERE TS.STATUS_ID = 3 AND
		(TS.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
		(TS.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
		(TS.DRIVER_ID = p_driver_id OR p_driver_id IS NULL)
	GROUP BY TS.transport_id, TS.driver_id, TS.branch_id, B.full_name, TM.full_name, T.state_code, T.state_number, P.full_name;
END;
$$ LANGUAGE plpgsql;