namespace Bms.Core.Domain;

public enum ErrorCode
{
    #region CLIENT ERRORS
    CLIENT_NOT_NULL_PROPERTY = 1001,
    CLIENT_INVALID_PROPERTY_FORMAT = 1002,
    CLIENT_NOT_FOUND = 1003,
    CLIENT_WRONG_STATUS = 1004,
    CLIENT_CREDENTIALS = 1005,
    CLIENT_ALREADY_EXISTS = 1006,
    CLIENT_NOT_ALLOWED_STATUS = 1007,
    CLIENT_NO_PERMISSION = 1008,
    CLIENT_NOT_ENAUGH = 1009,
    CLIENT_CAN_NOT_PASSIVE = 1010,
    CLIENT_PROPS_MUST_NOT_EQUAL = 1011,
    #endregion


    #region SERVER ERRORS
    SERVER_NOT_EXPECTED = 3001,
    SERVER_NOT_WORKING_EXCEPTION = 3002,
    SERVER_NOT_WORKING_DATABASE = 3003,
    #endregion


    #region INTERNAL INTEGRATION
    SERVER_NOT_WORKING_CASH_MANAGMENT = 4001,
    #endregion


    #region EXTERNAL INTEGRATION
    SERVER_NOT_WORKING_GSP = 5001
    #endregion
}
