CREATE TABLE adm.info_template (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    
    order_code              VARCHAR(4),
    code                    VARCHAR(20)                 NOT NULL,
    short_name              VARCHAR(250)                NOT NULL,
    full_name               VARCHAR(250)                NOT NULL,
    
    state_id                INTEGER                     NOT NULL,
    
    created_at              TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    last_modified_at        TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by        BIGINT,
    
    CONSTRAINT pk_adm__info_template 
        PRIMARY KEY (id),
        
    CONSTRAINT fk_adm__info_template__state_id 
        FOREIGN KEY (state_id) 
        REFERENCES adm.enum_state (id)
);


INSERT INTO adm.sys_table (id, short_name, full_name, db_schema_name, db_table_name, table_type)
 VALUES (0, 'info_template', 'info_template', 'ADM', 'info_template', 'INFO');