CREATE TABLE ENUM_STATE
(
	ID 			INT NOT NULL PRIMARY KEY,
	ORDER_CODE 	VARCHAR(5),
	SHORT_NAME	VARCHAR(250) NOT NULL,
	FULL_NAME	VARCHAR(500) NOT NULL,
	IS_DELETED	BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);
