INSERT INTO HL_PERSON (DOCUMENT_TYPE_ID,DOCUMENT_SERIA,DOCUMENT_NUMBER,BIRTH_ON,LAST_NAME,FIRST_NAME,FULL_NAME,GENDER_ID,STATE_ID)
VALUES (1,N'AA', N'0000000',now(), N'Administrator', N'Administrator',N'Administrator', 1, 1);
