CREATE TABLE HL_POSITION
(
 	ID              INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
 	SHORT_NAME      VARCHAR(250) NOT NULL,
 	FULL_NAME       VARCHAR(250) NOT NULL,
 	CODE            VARCHAR(50) NOT NULL,
 	ORDER_CODE      VARCHAR(50) NULL,
	 
 	STATE_ID        INT NOT NULL,
	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT    	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT NULL,
	MODIFIED_AT   	TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY   	INT,
	
 	CONSTRAINT FK_STATE_ID
	 	FOREIGN KEY ( STATE_ID )
		 	REFERENCES ENUM_STATE ( ID )
);