
INSERT INTO SYS_USER 
(USER_NAME, PASSWORD_HASH, PASSWORD_SALT,ORGANIZATION_ID, PERSON_ID, STATE_ID)
(SELECT 
	N'admin', 
	N'PC8cKGwdNDgTjEhMElJE3cy6Xhz0+PsBoibo4r4wteaMItXc5RdWIKClP23yKcXu58+7dI6gl6peMtvYM8XnTA==', 
	N'vfzuPA==',
	(SELECT ID FROM INFO_ORGANIZATION LIMIT 1), 
	(SELECT ID FROM HL_PERSON LIMIT 1), 
	1
);
