CREATE TABLE SYS_USER_LOG (
	ID				INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,

	ACTION_NAME     VARCHAR(200) NOT NULL,
	USER_NAME       VARCHAR(250) NOT NULL,
	USER_ID         INT NULL,
	IP_ADDRESS      VARCHAR(200),
	USER_AGENT		VARCHAR(2000),
	
	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);