CREATE TABLE QR.ENUM_QR_CODE_STATE (
  ID                INT NOT NULL PRIMARY KEY,
  SHORT_NAME        VARCHAR(250) NOT NULL,
  FULL_NAME         VARCHAR(500) NOT NULL,  
  
  IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
  CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);