INSERT INTO QR.ENUM_QR_CODE_STATE(ID, SHORT_NAME, FULL_NAME) VALUES (1, E'А', E'Актив');
INSERT INTO QR.ENUM_QR_CODE_STATE(ID, SHORT_NAME, FULL_NAME) VALUES (2, E'П', E'Пассив');
INSERT INTO QR.ENUM_QR_CODE_STATE(ID, SHORT_NAME, FULL_NAME) VALUES (3, E'Р', E'Резерв');