CREATE TABLE QR.DOC_MACHINE_READABLE_CODE_SETTING_HISTORY
(
  ID 				 BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  OWNER_ID 			 BIGINT NOT NULL,
  STATUS_ID			 INT NOT NULL,
  MESSAGE 			 VARCHAR(1000),
  USER_INFO			 VARCHAR(1000) NOT NULL,
  DATA_JSON		  	 JSONB NOT NULL,

  IS_DELETED		 BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT		 TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY		 INT,
  
  CONSTRAINT FK_OWNER_ID 
  	FOREIGN KEY ( OWNER_ID ) 
	  	REFERENCES QR.DOC_MACHINE_READABLE_CODE_SETTING ( ID ),
  CONSTRAINT FK_STATUS_ID 
  	FOREIGN KEY ( STATUS_ID )
	  REFERENCES ENUM_STATUS ( ID )
);