CREATE TABLE QR.DOC_MACHINE_READABLE_CODE_SETTING_TABLE
(
	ID			 				BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,
	CODE_FORM_TYPE_ID			INT,

	HAS_PREFEX					BOOL NOT NULL,
	IS_UUID						BOOL NOT NULL,

	PREFEX						VARCHAR(10),
	NEXT_TEMPLATE_LENGTH		INT,
	NEXT_TEMPLATE_LETTER_COUNT	INT,
	NEXT_TEMPLATE_NUMBER_COUNT	INT,

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
  	CREATED_AT			   		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  	CREATED_BY			   		INT,
  	MODIFIED_AT			   		TIMESTAMP WITHOUT TIME ZONE,
  	MODIFIED_BY			   		INT,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES QR.DOC_MACHINE_READABLE_CODE_SETTING(ID),
	CONSTRAINT FK_CODE_FORM_TYPE_ID
		FOREIGN KEY (CODE_FORM_TYPE_ID)
			REFERENCES QR.ENUM_CODE_FORM_TYPE (ID)
);

CREATE INDEX INDX_DOC_MACH_READ_SET_TAB_OWNID
	ON QR.DOC_MACHINE_READABLE_CODE_SETTING_TABLE (OWNER_ID);