CREATE TABLE QR.SYS_QR_CODE_REGISTRY (
  ID                       UUID NOT NULL PRIMARY KEY,
  UNIQUE_KEY               VARCHAR(50) NOT NULL,
	
  QR_CODE_TYPE_ID          INTEGER NOT NULL, 
  QR_CODE_VERSION          INTEGER NOT NULL, 
  
  DOCUMENT_ID              BIGINT, 
  DOCUMENT_ID_AS_GUID      UUID,
  EXTENDS                  VARCHAR,
  
  QR_CODE_STATE_ID         INTEGER NOT NULL, 
  EXPIRE_AT                TIMESTAMP WITHOUT TIME ZONE,

  ORGANIZATION_ID          INTEGER NOT NULL,
  PARENT_ID				   UUID,
  SETTINGS_DOC_ID		   BIGINT,

  IS_DELETED 			   BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT			   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY			   INT,
  MODIFIED_AT			   TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY			   INT,


  CONSTRAINT FK_QR_CODE_TYPE_ID
    FOREIGN KEY (QR_CODE_TYPE_ID)
  	  	REFERENCES QR.ENUM_QR_CODE_TYPE(ID),
  CONSTRAINT FK_QR_CODE_STATE_ID
    FOREIGN KEY (QR_CODE_STATE_ID)
   	 	REFERENCES QR.ENUM_QR_CODE_STATE(ID),
  CONSTRAINT FK_ORGANIZATION_ID
    FOREIGN KEY (ORGANIZATION_ID)
    	REFERENCES INFO_ORGANIZATION(ID),
  CONSTRAINT FK_PARENT_ID
    FOREIGN KEY (PARENT_ID)
    	REFERENCES QR.SYS_QR_CODE_REGISTRY(ID),
  CONSTRAINT FK_SETTINGS_DOC_ID
    FOREIGN KEY (SETTINGS_DOC_ID)
    	REFERENCES QR.DOC_MACHINE_READABLE_CODE_SETTING(ID)
);

CREATE UNIQUE INDEX UIX__SYS_QR_CODE_REGISTRY_UNIQUE_KEY
  ON QR.SYS_QR_CODE_REGISTRY
  (UNIQUE_KEY);
  
CREATE INDEX IX__SYS_QR_CODE_REGISTRY_CD_TYPEID_UNIQUE_KEY
  ON QR.SYS_QR_CODE_REGISTRY
  (QR_CODE_TYPE_ID, UNIQUE_KEY);
  
CREATE INDEX IX__SYS_QR_CODE_REGISTRY_TYPEID_DOCID
  ON QR.SYS_QR_CODE_REGISTRY
  (QR_CODE_TYPE_ID, DOCUMENT_ID);