CREATE TABLE HL_DRIVER
(
	ID						INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

	PERSON_ID				BIGINT NOT NULL,
	BRANCH_ID				INT NOT NULL,
	UNIQUE_CODE				UUID NOT NULL, --BRILOGI UCHUN	

	QR_CODE_REGISTRY_ID		UUID,
	STATE_ID				INT NOT NULL,

	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,	
	
	CONSTRAINT FK_PERSON_ID	
		FOREIGN KEY (PERSON_ID)
			REFERENCES HL_PERSON (ID),	
	CONSTRAINT FK_BRANCH_ID	
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),	
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),
	CONSTRAINT FK_QR_CODE_REGISTRY_ID
		FOREIGN KEY (QR_CODE_REGISTRY_ID)
			REFERENCES QR.SYS_QR_CODE_REGISTRY (id)
);

CREATE UNIQUE INDEX UIX__HL_DRIVER__BRID_PERID_STID
	ON HL_DRIVER (BRANCH_ID,PERSON_ID,STATE_ID)
	WHERE STATE_ID = 1;
CREATE UNIQUE INDEX UIX__HL_DRIVER__UNIQCD
	ON HL_DRIVER(UNIQUE_CODE)
	WHERE STATE_ID = 1;