CREATE TABLE HL_TRANSPORT_MODEL_FILE
(
    ID                  UUID NOT NULL PRIMARY KEY, 
    FILE_NAME           VARCHAR(250) NOT NULL,
    TRANSPORT_MODEL_ID  INT NOT NULL,
    TRANSPORT_COLOR_ID  INT NOT NULL,

    IS_DELETED          BOOL NOT NULL DEFAULT FALSE,
    CREATED_AT          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATED_BY          INT,
    MODIFIED_AT         TIMESTAMP WITHOUT TIME ZONE,
    MODIFIED_BY         INT,

    CONSTRAINT FK_TRANSPORT_MODEL_ID
        FOREIGN KEY (TRANSPORT_MODEL_ID)
        REFERENCES INFO_TRANSPORT_MODEL (ID) ON DELETE CASCADE,

    CONSTRAINT FK_TRANSPORT_COLOR_ID
        FOREIGN KEY (TRANSPORT_COLOR_ID)
        REFERENCES INFO_TRANSPORT_COLOR (ID) ON DELETE CASCADE,

    CONSTRAINT UQ_TRANSPORT_MODEL_COLOR UNIQUE (TRANSPORT_MODEL_ID, TRANSPORT_COLOR_ID)
);

CREATE INDEX INDX__HL_TRNSPRT_MDL_CLR
    ON HL_TRANSPORT_MODEL_FILE(TRANSPORT_MODEL_ID, TRANSPORT_COLOR_ID);
