CREATE TABLE DOC_TRANSPORT_SETTING_BATTERY -- Аккумулятор
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	QUANTITY					INT NOT NULL, --количество
	BATTERY_TYPE_ID				INT NOT NULL, --ТИП
	PRODUCED_AT					DATE NOT NULL, --Дата
	MILE_AGE					NUMERIC(18,2) NOT NULL, --Пробег

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID),
	CONSTRAINT FK_BATTERY_TYPE_ID
		FOREIGN KEY (BATTERY_TYPE_ID)
			REFERENCES INFO_BATTERY_TYPE (ID)
);

CREATE INDEX INDX_DOC_TRANSPORT_SETTING_BATTERY_OWN_ID
	ON DOC_TRANSPORT_SETTING_BATTERY (OWNER_ID);