CREATE TABLE DOC_TRANSPORT_SETTING_OIL -- масла
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	OIL_TYPE_ID					INT NOT NULL, --Тип масла ДВС
	TANK_VOLUME					NUMERIC(18,2) NOT NULL, --Объем в двигателе
	MONTHLY_LIMIT				NUMERIC(18,2) NOT NULL, --Лимит доливки на месяц
	REMAINING					NUMERIC(18,2) NOT NULL DEFAULT 0, --Остаток на момент заведения

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID),
	CONSTRAINT FK_OIL_TYPE_ID
		FOREIGN KEY (OIL_TYPE_ID)
			REFERENCES INFO_OIL_TYPE (ID)
);

CREATE INDEX INDX_DOC_TRANSPORT_SETTING_OIL_OWN_ID
	ON DOC_TRANSPORT_SETTING_OIL (OWNER_ID);

CREATE UNIQUE INDEX UINDX__DOC_TR_SET_OIL_OWNID_ISDEL
	ON DOC_TRANSPORT_SETTING_OIL (OWNER_ID,IS_DELETED)
		WHERE IS_DELETED = FALSE;