CREATE TABLE DOC_TRANSPORT_SETTING_INSPECTION -- TO
(
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID					BIGINT NOT NULL,

	DATE_AT						DATE NOT NULL,		--Дата прохождения ТО
	EXPIRE_AT					DATE NOT NULL,		--Срок действия
	RESPONSIBLE_PERSON_ID		BIGINT NOT NULL,	--ФИО ответственного за ТО

	DETAILS						TEXT,
	NOTIFY_BEFORE_DAY			INT NOT NULL, --За сколько дней оповестить ответственного

	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_TRANSPORT_SETTING (ID),
	CONSTRAINT FK_RESPONSIBLE_PERSON_ID
		FOREIGN KEY (RESPONSIBLE_PERSON_ID)
			REFERENCES HL_PERSON (ID)
);

CREATE UNIQUE INDEX UINDX__DOC_TR_SET_INSP_OWNID_ISDEL
	ON DOC_TRANSPORT_SETTING_INSPECTION (OWNER_ID,IS_DELETED)
		WHERE IS_DELETED = FALSE;