CREATE TABLE SYS_NUMBER (
  ID                        INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,  
  DOCUMENT                  VARCHAR(100) NOT NULL,  
  CURRENT_NUMBER            INT NOT NULL,
  ORGANIZATION_ID           INT NOT NULL,
  BRANCH_ID                 INT NOT NULL,
  FINANCE_YEAR              INT NOT NULL,
  IS_DELETED				 BOOL NOT NULL,
  CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY				INT,
  MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY				INT,	

  CONSTRAINT FK_ORGANIZATION_ID
    FOREIGN KEY (ORGANIZATION_ID)
    REFERENCES INFO_ORGANIZATION(id)
	ON DELETE CASCADE,
    
  CONSTRAINT FK_BRANCH_ID
    FOREIGN KEY (BRANCH_ID) REFERENCES HL_BRANCH(id)
	ON DELETE CASCADE
);
