CREATE TABLE HL_NUMBER_TEMPLATE
(
    ID                       SERIAL NOT NULL PRIMARY KEY,
    DATE                     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    DOCUMENT                 VARCHAR(100) NOT NULL,
    TEMPLATE                 VARCHAR(250) NOT NULL,
    ORGANIZATION_ID          INT NOT NULL,
    CREATED_AT         	      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY                INT,
    MODIFIED_AT               TIMESTAMP WITHOUT TIME ZONE,
    MODIFIED_BY        		   INT ,

    CONSTRAINT FK_ORGANIZATION_ID
        FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES PUBLIC.INFO_ORGANIZATION (ID)

);