CREATE TABLE SYS_USER_REFRESH_TOKEN
(
    ID                      UUID NOT NULL PRIMARY KEY,
    USER_ID                 INT NOT NULL,
    EXPIRE_AT               TIMESTAMP (6) NOT NULL,
    TOKEN_HASH              VARCHAR NOT NULL,
    IS_DELETED              BOOL NOT NULL, 

  	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,
   
    CONSTRAINT FK_USER_ID
		FOREIGN KEY ( USER_ID ) 
			REFERENCES SYS_USER ( ID )
);

CREATE INDEX INDX_SYS_USER_REFRESH_TOKEN_ISDEL_USER_ID_EXPIRE_AT ON SYS_USER_REFRESH_TOKEN (IS_DELETED,USER_ID, EXPIRE_AT);
CREATE INDEX INDX_SYS_USER_REFRESH_TOKEN_ISDEL_HASH_EXPIRE_AT ON SYS_USER_REFRESH_TOKEN (IS_DELETED,TOKEN_HASH,EXPIRE_AT);