CREATE TABLE HL_FUEL_CARD
(
    ID                        INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    DRIVER_ID                 INT,
    TRANSPORT_ID              INT,
    PLASTIC_CARD_TYPE_ID      INT NOT NULL,
    CARD_NUMBER               VARCHAR(50) NOT NULL,
    EXPIRE_AT                 DATE,
	STATE_ID				  INT NOT NULL,
    BRANCH_ID                 INT,  

	IS_DELETED				  BOOL NOT NULL DEFAULT FALSE,
    CREATED_AT         	      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY                INT,
    MODIFIED_AT               TIMESTAMP WITHOUT TIME ZONE,
    MODIFIED_BY        		  INT ,

    CONSTRAINT FK_DRIVER_ID
        FOREIGN KEY (DRIVER_ID)
            REFERENCES HL_DRIVER (ID),
    CONSTRAINT FK_TRANSPORT_ID
        FOREIGN KEY (TRANSPORT_ID)
            REFERENCES HL_TRANSPORT (ID),
    CONSTRAINT FK_PLASTIC_CARD_TYPE_ID
        FOREIGN KEY(PLASTIC_CARD_TYPE_ID)
             REFERENCES ENUM_PLASTIC_CARD_TYPE (ID),
	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID) ,
    CONSTRAINT FK_BRANCH_ID
        FOREIGN KEY (BRANCH_ID)
            REFERENCES HL_BRANCH (ID)
);

CREATE UNIQUE INDEX UIX__HL_FL_CRD__CARDNUM
    ON HL_FUEL_CARD (CARD_NUMBER);

--CREATE UNIQUE INDEX UIX__HL_FL_CRD__STID_DRVRID
	--ON HL_FUEL_CARD (STATE_ID , DRIVER_ID);

CREATE UNIQUE INDEX UIX__HL_FL_CRD__STID_TRNPTID
	ON HL_FUEL_CARD (STATE_ID , TRANSPORT_ID);