CREATE TABLE DOC_REFUEL_HISTORY
(
  ID 				 BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
  OWNER_ID 			 BIGINT NOT NULL,
  STATUS_ID			 INT NOT NULL,
  MESSAGE 			 VARCHAR(1000),
  USER_INFO			 VARCHAR(1000) NOT NULL,
  DATA_JSON		  	 JSONB, -- this is optional.We are not going to save this in db but in MINIO 
  HISTORY_FILE_ID    UUID NOT NULL, -- this is optional in our situation

  IS_DELETED		 BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT		 TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY		 INT,
  
  CONSTRAINT FK_OWNER_ID 
  	FOREIGN KEY ( OWNER_ID ) 
	  	REFERENCES DOC_REFUEL ( ID ),
  CONSTRAINT FK_STATUS_ID 
  	FOREIGN KEY ( STATUS_ID )
	  REFERENCES ENUM_STATUS ( ID )
);

CREATE INDEX INDX__DOC_REFUEL_HIS__OWNID
    ON DOC_REFUEL_HISTORY(OWNER_ID);