CREATE TABLE ACC_DRIVER_PENALTY
(	
	ID							BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	
	BRANCH_ID					INT NOT NULL,
	PERSON_ID					BIGINT NOT NULL,
	TRANSPORT_ID				INT NOT NULL,
	REGISTRATION_NUMBER			VARCHAR(50) NOT NULL, -- transport.state_code+transport.state_number in our database
		
	EXTERNAL_ID					BIGINT NOT NULL,
	FIRST_NAME_LAT				VARCHAR(100) NOT NULL,
	SECOND_NAME_LAT				VARCHAR(100) NOT NULL,
	LAST_NAME_LAT				VARCHAR(100) NOT NULL,
	
	AMOUNT						NUMERIC(18,2) NOT NULL DEFAULT 0,
	PAID_AMOUNT					NUMERIC(18,2) NOT NULL DEFAULT 0,
	LAST_PAY_TIME				TIMESTAMP WITHOUT TIME ZONE,
		
	CASE_ORGAN					VARCHAR(300),
	DECISION_ORGAN				VARCHAR(300),
	DECISION_ARTICLE_PART		VARCHAR(50),
	DECISION_CITY				VARCHAR(200),
	DECISION_PASSPORT			VARCHAR(50),
	DECISION_STATUS			    VARCHAR(50),
	DECISION_TIME			    TIMESTAMP WITHOUT TIME ZONE,
	DECISION_VIOLATION_TYPE		VARCHAR(50),
	DECISION_PDF				VARCHAR(500),
	
	DISCOUNT50_AMOUNT			NUMERIC(18,2) NOT NULL DEFAULT 0,
	DISCOUNT50_DATE				DATE,
	DISCOUNT_AMOUNT				NUMERIC(18,2) NOT NULL DEFAULT 0,
	DISCOUNT_DATE				DATE,
	
	INVOICE_IS_ACTIVE			BOOL,
	INVOICE_SERIAL				VARCHAR(50),
	
	MIB_CASE_NUMBER				VARCHAR(100),
	MIB_CASE_STATUS				VARCHAR(50),
	MIB_SEND_TIME				TIMESTAMP WITHOUT TIME ZONE,
	
	IS_DELETED					BOOL NOT NULl,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

	CONSTRAINT FK_BRANCH_ID
		FOREIGN KEY (BRANCH_ID)
			REFERENCES HL_BRANCH (ID),
	CONSTRAINT FK_PERSON_ID
		FOREIGN KEY (PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_TRANSPORT_ID
		FOREIGN KEY (TRANSPORT_ID)
			REFERENCES HL_TRANSPORT (ID)
);

CREATE INDEX INDX__ACC_DRVR_PLTY__BRCH_ID
	ON ACC_DRIVER_PENALTY (BRANCH_ID);
CREATE INDEX INDX__ACC_DRVR_PLTY__PER_ID
	ON ACC_DRIVER_PENALTY (PERSON_ID);
CREATE INDEX INDX__ACC_DRVR_PLTY__TRPRT_ID
	ON ACC_DRIVER_PENALTY (TRANSPORT_ID);