
ALTER TABLE DOC_TRANSPORT_SETTING
ADD COLUMN BRANCH_ID INT DEFAULT 1 NOT NULL;

ALTER TABLE DOC_TRANSPORT_SETTING
 ADD CONSTRAINT FK_BRANCH_ID
	FOREIGN KEY ( BRANCH_ID ) 
		REFERENCES HL_BRANCH ( ID );

ALTER TABLE DOC_TRANSPORT_SETTING
ADD COLUMN MANAGER_ID BIGINT;

ALTER TABLE DOC_TRANSPORT_SETTING
ADD CONSTRAINT FK_MANAGER_ID
    FOREIGN KEY (MANAGER_ID)
    REFERENCES HL_PERSON (ID) ON DELETE SET NULL;

