CREATE TABLE DOC_TRANSPORT_SETTING_FILE
(
    ID                          UUID NOT NULL PRIMARY KEY,
    OWNER_ID                    BIGINT NOT NULL,
    FILE_NAME                   VARCHAR(250) NOT NULL, 

	IS_DELETED				    BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,

    CONSTRAINT FK_OWNER_ID 
        FOREIGN KEY (OWNER_ID)
            REFERENCES DOC_TRANSPORT_SETTING(ID)
                ON DELETE CASCADE
);

CREATE INDEX INDX__DOC_TRNSPRT_SET_FL__OWNID
    ON DOC_TRANSPORT_SETTING_FILE(OWNER_ID);