CREATE TABLE ENUM_TRANSMISSION_BOX_TYPE --Karobka turi (Avtomat,Mexanika)
(
	ID				INT NOT NULL PRIMARY KEY,
	ORDER_CODE		VARCHAR(5),
	
	SHORT_NAME		VARCHAR(250) NOT NULL,
	FULL_NAME		VARCHAR(250) NOT NULL,
	
	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	STATE_ID		INT NOT NULL,	  
 	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,

	CONSTRAINT FK_STATE_ID	
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);