CREATE TABLE INFO_TRANSPORT_MODEL_LIQUID
(
	ID							INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
	
	OWNER_ID					INT NOT NULL,
	LIQUID_TYPE_ID				INT NOT NULL,
	TANK_VOLUME					NUMERIC(18,2) NOT NULL,
	
	IS_DELETED					BOOL NOT NULL DEFAULT FALSE,
  	CREATED_AT					TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY					INT,
	MODIFIED_AT					TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY					INT,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES INFO_TRANSPORT_MODEL (ID),
	CONSTRAINT FK_LIQUID_TYPE_ID
		FOREIGN KEY (LIQUID_TYPE_ID)
			REFERENCES INFO_LIQUID_TYPE (ID)
);