ALTER TABLE INFO_TRANSPORT_MODEL
	ADD COLUMN SEAT_COUNT INT NOT NULL DEFAULT 4,
	ADD COLUMN LOAD_CAPACITY NUMERIC(18,2) NOT NULL DEFAULT 0,
	ADD COLUMN TRANSMISSION_BOX_TYPE_ID INT NOT NULL DEFAULT 1;

ALTER TABLE INFO_TRANSPORT_MODEL
	ALTER COLUMN SEAT_COUNT DROP DEFAULT;
	
ALTER TABLE INFO_TRANSPORT_MODEL
	ALTER COLUMN LOAD_CAPACITY DROP DEFAULT;

ALTER TABLE INFO_TRANSPORT_MODEL
	ALTER COLUMN TRANSMISSION_BOX_TYPE_ID DROP DEFAULT;