ALTER TABLE INFO_TRANSPORT_MODEL
	ADD CONSTRAINT FK_TRANSMISSION_BOX_TYPE_ID 
		FOREIGN KEY (TRANSMISSION_BOX_TYPE_ID)
			REFERENCES ENUM_TRANSMISSION_BOX_TYPE (ID);

ALTER TABLE INFO_TRANSPORT_MODEL
ADD COLUMN TRANSPORT_MODEL_LIQUID_ID INT NOT NULL DEFAULT 1;