CREATE TABLE HL_TRACKING_INFO (
    ID              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    PERSON_ID       BIGINT NOT NULL,
    LATITUDE        NUMERIC(18,6) NOT NULL,
    LONGITUDE       NUMERIC(18,6) NOT NULL,
    DATE_AT         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATED_AT      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CREATED_BY      INT,    

    CONSTRAINT FK_HL_TRACKING_INFO_PERSON
        FOREIGN KEY (PERSON_ID)
        REFERENCES HL_PERSON (ID) ON DELETE CASCADE
);
