CREATE TABLE DOC_NOTIFICATION_TEMPLATE_SETTING
(
  ID                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

  DOC_NUMBER              VARCHAR(50) NOT NULL,
  DOC_DATE                DATE NOT NULL,
  
  NOTIFICATION_TEMPLATE_ID    INT NOT NULL,
  BRANCH_ID                  INT,

  IS_DELETED          BOOL NOT NULL DEFAULT FALSE,
  STATUS_ID          INT NOT NULL,
  CREATED_AT          TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY          INT,
  MODIFIED_AT          TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY          INT,

  CONSTRAINT FK_STATUS_ID
  FOREIGN KEY (STATUS_ID)
    REFERENCES ENUM_STATUS (ID),
    
  CONSTRAINT FK_NOTIFICATION_TEMPLATE_ID
    FOREIGN KEY (NOTIFICATION_TEMPLATE_ID)
      REFERENCES ENUM_NOTIFICATION_TEMPLATE (ID),

  CONSTRAINT FK_BRANCH_ID
    FOREIGN KEY (BRANCH_ID)
      REFERENCES HL_BRANCH(ID)
);

CREATE UNIQUE INDEX IDX_NT_STATUS_ACCEPT 
ON DOC_NOTIFICATION_TEMPLATE_SETTING(NOTIFICATION_TEMPLATE_ID) 
WHERE STATUS_ID = 3; --THERE MUST BE ONLY ONE SETTING IN THE ACCEPTED STATUS