CREATE TABLE DOC_NOTIFICATION_TEMPLATE_SETTING_ROLE 
(
  ID                        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

  OWNER_ID                BIGINT NOT NULL,
  ROLE_ID                INT NOT NULL,

  IS_DELETED                BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY                INT,
  MODIFIED_AT               TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY               INT,

  CONSTRAINT FK_OWNER_ID
    FOREIGN KEY (OWNER_ID)
      REFERENCES DOC_NOTIFICATION_TEMPLATE_SETTING(ID)
        ON DELETE CASCADE,

  CONSTRAINT FK_ROLE_ID
    FOREIGN KEY (ROLE_ID)
      REFERENCES SYS_ROLE(ID),

  CONSTRAINT UIX_NR_TEMPLATE_USER__OWID_RLID
    UNIQUE(OWNER_ID, ROLE_ID)
);