CREATE TABLE DOC_NOTIFICATION_TEMPLATE_SETTING_RESTRICTED_USER
(
  ID                        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,

  OWNER_ID                	BIGINT NOT NULL,
  USER_ID                	INT NOT NULL,

  IS_DELETED                BOOL NOT NULL DEFAULT FALSE,
  CREATED_AT                TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  CREATED_BY                INT,
  MODIFIED_AT               TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY               INT,

  CONSTRAINT FK_OWNER_ID
    FOREIGN KEY (OWNER_ID)
      REFERENCES DOC_NOTIFICATION_TEMPLATE_SETTING(ID)
        ON DELETE CASCADE,
  CONSTRAINT FK_USER_ID
      FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER(ID),

  CONSTRAINT UIX_NRU_TEMPLATE_RESTRICTED_USER_OWNID_USID
    UNIQUE(OWNER_ID, USER_ID)
);