CREATE TABLE INFO_MOBILE_APP_VERSION
(
	ID          		UUID NOT NULL PRIMARY KEY,
	FILE_NAME        	VARCHAR(250) NOT NULL, 
  	VERSION_CODE      	VARCHAR(50) NOT NULL,
  	DETAILS        		VARCHAR(1000),
  	RELEASE_AT      	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
  	STATE_ID        	INT NOT NULL,  
  
    CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
  
  	CONSTRAINT FK_STATE_ID
    	FOREIGN KEY (STATE_ID)
      		REFERENCES ENUM_STATE (id)
);

CREATE UNIQUE INDEX UIX__INFO_MOBILE_APP_VERSION__VERSION_CODE
  ON INFO_MOBILE_APP_VERSION (VERSION_CODE);