CREATE TABLE DOC_EXPENSE_TIRE
(
	ID 					BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID			BIGINT NOT NULL,
	TIRE_SIZE_ID		INT NOT NULL,
	DATE_ON				DATE NOT NULL,
	
	QUANTITY			NUMERIC(18,2) NOT NULL DEFAULT 0,
	PRICE				NUMERIC(18,2) NOT NULL DEFAULT 0,
	TOTAL_PRICE			NUMERIC(18,2) NOT NULL DEFAULT 0,
	
	INVOICE_NUMBER		VARCHAR(50),
	INVOICE_DATE_ON		DATE,
	
	IS_DELETED			BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_EXPENSE(ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_TIRE_SIZE_ID
		FOREIGN KEY (TIRE_SIZE_ID)
			REFERENCES INFO_TIRE_SIZE (ID)
);

CREATE INDEX INDX_DOC_EXPENSE_TIRE_OWNR_ID
	ON DOC_EXPENSE_TIRE (OWNER_ID);