CREATE TABLE ENUM_INSPECTION_TYPE_TRANSLATE 
(
	ID 				INT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID		INT NOT NULL,
	LANGUAGE_ID		INT NOT NULL,
	COLUMN_NAME		VARCHAR(100) NOT NULL,
	TRANSLATE_TEXT 	TEXT NOT NULL,

	IS_DELETED		BOOL NOT NULL DEFAULT FALSE,	
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE 
								DEFAULT NOW() NOT NULL,
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID) 
			REFERENCES ENUM_INSPECTION_TYPE (ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_LANGUAGE_ID 
		FOREIGN KEY (LANGUAGE_ID)
			REFERENCES ENUM_LANGUAGE (ID)
);
