CREATE TABLE DOC_EXPENSE_INSPECTION
(
	ID 						BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID				BIGINT NOT NULL,
	DATE_ON					DATE NOT NULL,
	INSPECTION_TYPE_ID		INT NOT NULL,
	DETAILS					TEXT,
	
	PRICE					NUMERIC(18,2) NOT NULL DEFAULT 0,
	INVOICE_NUMBER			VARCHAR(50),
	INVOICE_DATE_ON			DATE,
	
	IS_DELETED				BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_EXPENSE(ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_INSPECTION_TYPE_ID
		FOREIGN KEY (INSPECTION_TYPE_ID)
			REFERENCES ENUM_INSPECTION_TYPE
);

CREATE INDEX INDX_DOC_EXPENSE_INSPECTION_OWNR_ID
	ON DOC_EXPENSE_INSPECTION  (OWNER_ID);