
CREATE TABLE DOC_EXPENSE_INSURANCE
(
	ID 					BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
	OWNER_ID			BIGINT NOT NULL,
	DATE_ON				DATE NOT NULL,
	INSURANCE_TYPE_ID	INT NOT NULL,
	INS_NUMBER			VARCHAR(50) NOT NULL,
	CONTRACTOR_ID		BIGINT NOT NULL,
		
	PRICE				NUMERIC(18,2) NOT NULL DEFAULT 0,
	INVOICE_NUMBER		VARCHAR(50),
	INVOICE_DATE_ON		DATE,
	
	IS_DELETED			BOOL NOT NULL DEFAULT FALSE,
	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES DOC_EXPENSE(ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_INSURANCE_TYPE_ID
		FOREIGN KEY (INSURANCE_TYPE_ID)
			REFERENCES INFO_INSURANCE_TYPE (ID),
	CONSTRAINT FK_CONTRACTOR_ID
		FOREIGN KEY (CONTRACTOR_ID)
			REFERENCES INFO_CONTRACTOR (ID)
);

CREATE INDEX INDX_DOC_EXPENSE_INSURANCE_OWNR_ID
	ON DOC_EXPENSE_INSURANCE (OWNER_ID);