CREATE OR REPLACE FUNCTION public.get_expense(
	p_branch_id integer,
	p_transport_id integer,
	p_driver_id integer,
	p_from_date timestamp without time zone,
	p_to_date timestamp without time zone)
RETURNS TABLE(
	EXPENSE_DATE timestamp without time zone, 
	EXPENSE_TYPE_ID INTEGER, 
	BRAND VARCHAR, 
	QUANTITY numeric, 
	PRICE NUMERIC(18,2), 
	EXPENSE_PRICE NUMERIC(18,2)
)AS $$
BEGIN
RETURN QUERY
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		3 AS EXPENSE_TYPE_ID,
		BT.FULL_NAME AS BRAND,
		EB.QUANTITY AS QUANTITY,
		EB.PRICE AS PRICE,
		EB.TOTAL_PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_BATTERY AS EB ON E.ID = EB.OWNER_ID
	JOIN INFO_BATTERY_TYPE AS BT ON EB.battery_type_id = BT.id
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		5 AS EXPENSE_TYPE_ID,
		'Inspection' AS BRAND,
		1 AS QUANTITY,
		EIP.PRICE AS PRICE,
		EIP.PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_INSPECTION AS EIP ON E.ID = EIP.OWNER_ID
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND 
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL	
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		6 AS EXPENSE_TYPE_ID,
		IT.FULL_NAME AS BRAND,
		1 AS QUANTITY,
		EIU.PRICE AS PRICE,
		EIU.PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_INSURANCE AS EIU ON E.ID = EIU.OWNER_ID
	JOIN INFO_INSURANCE_TYPE AS IT ON EIU.insurance_type_id = IT.id
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		4 AS EXPENSE_TYPE_ID,
		'Tire' AS BRAND,
		ET.QUANTITY AS QUANTITY,
		ET.PRICE AS PRICE,
		ET.TOTAL_PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_TIRE AS ET ON E.ID = ET.OWNER_ID
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		2 AS EXPENSE_TYPE_ID,
		LT.FULL_NAME AS BRAND,
		EL.QUANTITY AS QUANTITY,
		EL.PRICE AS PRICE,
		EL.TOTAL_PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_LIQUID AS EL ON E.ID = EL.OWNER_ID
	JOIN INFO_LIQUID_TYPE AS LT ON EL.liquid_type_id = LT.id
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL
	SELECT 
		E.CREATED_AT AS EXPENSE_DATE,
		1 AS EXPENSE_TYPE_ID,
		OT.FULL_NAME AS BRAND,
		EO.QUANTITY AS QUANTITY,
		EO.PRICE AS PRICE,
		EO.TOTAL_PRICE AS EXPENSE_PRICE
	FROM DOC_EXPENSE AS E
	JOIN DOC_EXPENSE_OIL AS EO ON E.ID = EO.OWNER_ID
	JOIN INFO_OIL_TYPE AS OT ON EO.oil_type_id = OT.id
	WHERE
		E.STATUS_ID = 3 AND
		E.TRANSPORT_ID = p_transport_id AND
		E.DRIVER_ID = p_driver_id AND
		E.BRANCH_ID = p_branch_id AND
		(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(E.MODIFIED_AT <= p_to_date OR p_to_date IS NULL)
	UNION ALL
	SELECT 
		R.CREATED_AT AS EXPENSE_DATE,
		7 AS EXPENSE_TYPE_ID,
		FT.FULL_NAME AS BRAND,
		R.LITRE AS QUANTITY,
		R.LITRE_PRICE AS PRICE,
		R.LITRE * R.LITRE_PRICE AS EXPENSE_PRICE
	FROM DOC_REFUEL AS R
	JOIN INFO_FUEL_TYPE AS FT ON R.fuel_type_id = FT.id
	WHERE
		R.STATUS_ID = 3 AND
		R.TRANSPORT_ID = p_transport_id AND
		R.DRIVER_ID = p_driver_id AND
		R.BRANCH_ID = p_branch_id AND
		(R.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND
		(R.MODIFIED_AT <= p_to_date OR p_to_date IS NULL);
END;
$$ LANGUAGE plpgsql;