ALTER TABLE public.doc_transport_setting_tire
ADD COLUMN TIRE_MODEL_ID INT;

ALTER TABLE public.doc_transport_setting_tire
	ADD CONSTRAINT FK_TIRE_MODEL_ID
		FOREIGN KEY (TIRE_MODEL_ID)
			REFERENCES INFO_TIRE_MODEL (ID);

ALTER TABLE public.doc_expense_tire
ADD COLUMN TIRE_MODEL_ID INT;

ALTER TABLE public.doc_expense_tire
	ADD CONSTRAINT FK_TIRE_MODEL_ID
		FOREIGN KEY (TIRE_MODEL_ID)
			REFERENCES INFO_TIRE_MODEL (ID);