-- FUNCTION: public.get_total_expense_over_limit(integer, integer, integer, timestamp without time zone, timestamp without time zone)

-- DROP FUNCTION IF EXISTS public.get_total_expense_over_limit(integer, integer, integer, timestamp without time zone, timestamp without time zone);

CREATE OR REPLACE FUNCTION public.get_total_expense_over_limit(
	p_branch_id integer,
	p_transport_id integer,
	p_driver_id integer,
	p_from_date timestamp without time zone,
	p_to_date timestamp without time zone)
    RETURNS TABLE(transport_id integer, driver_id integer, branch_id integer, branch_name character varying, transport_info character varying, driver character varying, total_sum numeric, is_over_limit boolean) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
BEGIN
RETURN QUERY
	WITH E_LIMIT AS(
	SELECT 
		TS.TRANSPORT_ID,
		TS.DRIVER_ID,
		SUM(COALESCE(TSL.MONTHLY_LIMIT, 0)) AS LIQUID_MONTHLY_LIMIT,
		SUM(COALESCE(TSO.MONTHLY_LIMIT, 0)) AS OIL_MONTHLY_LIMIT,
		SUM(COALESCE(TSF.MONTHLY_LIMIT, 0)) AS FUEL_MONTHLY_LIMIT
	FROM DOC_TRANSPORT_SETTING AS TS
	LEFT JOIN DOC_TRANSPORT_SETTING_LIQUID AS TSL ON TSL.OWNER_ID = TS.ID
	LEFT JOIN DOC_TRANSPORT_SETTING_OIL AS TSO ON TSO.OWNER_ID = TS.ID
	LEFT JOIN DOC_TRANSPORT_SETTING_FUEL AS TSF ON TSF.OWNER_ID = TS.ID
	WHERE TS.STATUS_ID = 3
	GROUP BY TS.TRANSPORT_ID, TS.DRIVER_ID
	), EXPENSE_PRICES_SUM AS(
		SELECT 
			E.TRANSPORT_ID AS TRANSPORT_ID,
			E.DRIVER_ID AS DRIVER_ID,
			COALESCE(SUM(EB.PRICE), 0) +
		    COALESCE(SUM(EIP.PRICE), 0) +
		    COALESCE(SUM(EIU.PRICE), 0) +
		    COALESCE(SUM(ET.PRICE), 0) +
		    COALESCE(SUM(EL.PRICE), 0) +
		    COALESCE(SUM(EO.PRICE), 0) AS TOTAL_EXPENSE_SUM,
			CASE WHEN COALESCE(SUM(EL.PRICE), 0) > MAX(E_LIMIT.LIQUID_MONTHLY_LIMIT) AND MAX(E_LIMIT.LIQUID_MONTHLY_LIMIT) <> 0 THEN TRUE
				 WHEN COALESCE(SUM(EO.PRICE), 0) > MAX(E_LIMIT.OIL_MONTHLY_LIMIT) AND MAX(E_LIMIT.LIQUID_MONTHLY_LIMIT) <> 0 THEN TRUE 
				 ELSE FALSE END AS LIMIT_IS_OVER
		
		FROM DOC_EXPENSE AS E
		LEFT JOIN DOC_EXPENSE_BATTERY AS EB ON E.ID = EB.OWNER_ID
		LEFT JOIN DOC_EXPENSE_INSPECTION AS EIP ON E.ID = EIP.OWNER_ID
		LEFT JOIN DOC_EXPENSE_INSURANCE AS EIU ON E.ID = EIU.OWNER_ID
		LEFT JOIN DOC_EXPENSE_TIRE AS ET ON E.ID = ET.OWNER_ID
		LEFT JOIN DOC_EXPENSE_LIQUID AS EL ON E.ID = EL.OWNER_ID
		LEFT JOIN DOC_EXPENSE_OIL AS EO ON E.ID = EO.OWNER_ID
		LEFT JOIN E_LIMIT ON E_LIMIT.TRANSPORT_ID = E.TRANSPORT_ID AND E_LIMIT.DRIVER_ID = E.DRIVER_ID
		WHERE E.STATUS_ID = 3 AND
			(E.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
			(E.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
			(E.DRIVER_ID = p_driver_id OR p_driver_id IS NULL) AND
			(E.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND (p_to_date IS NULL OR p_to_date >= E.MODIFIED_AT)
		GROUP BY E.TRANSPORT_ID, E.DRIVER_ID
	), REFUEL_PRICES_SUM AS(
		SELECT
			R.TRANSPORT_ID,
			R.DRIVER_ID,
			COALESCE(SUM(R.LITRE * R.LITRE_PRICE), 0) AS TOTAL_REFUEL_SUM,
			CASE 
				WHEN COALESCE(SUM(R.LITRE * R.LITRE_PRICE), 0) > MAX(E_LIMIT.FUEL_MONTHLY_LIMIT) THEN TRUE 
				ELSE FALSE END AS LIMIT_IS_OVER
		FROM DOC_REFUEL AS R
		LEFT JOIN E_LIMIT ON E_LIMIT.TRANSPORT_ID = R.TRANSPORT_ID AND E_LIMIT.DRIVER_ID = R.DRIVER_ID
		WHERE R.STATUS_ID = 3 AND
			(R.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
			(R.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
			(R.DRIVER_ID = p_driver_id OR p_driver_id IS NULL) AND
			(R.MODIFIED_AT >= p_from_date OR p_from_date IS NULL) AND (p_to_date >= R.MODIFIED_AT OR p_to_date IS NULL)
		GROUP BY R.TRANSPORT_ID, R.DRIVER_ID
	), GENERAL_EXPENSES AS(
		SELECT 
		    COALESCE(EPS.TRANSPORT_ID, RPS.TRANSPORT_ID) AS TRANSPORT_ID,
		    COALESCE(EPS.DRIVER_ID, RPS.DRIVER_ID) AS DRIVER_ID,
		    COALESCE(EPS.TOTAL_EXPENSE_SUM, 0) + COALESCE(RPS.TOTAL_REFUEL_SUM, 0) AS TOTAL_SUM,
			CASE WHEN EPS.LIMIT_IS_OVER IS TRUE OR RPS.LIMIT_IS_OVER IS TRUE THEN TRUE ELSE FALSE END AS LIMIT_IS_OVER
		FROM EXPENSE_PRICES_SUM EPS
		FULL OUTER JOIN REFUEL_PRICES_SUM RPS 
		    ON EPS.TRANSPORT_ID = RPS.TRANSPORT_ID AND EPS.DRIVER_ID = RPS.DRIVER_ID
	)
	
	SELECT
		TS.transport_id,
		TS.driver_id,
		TS.branch_id,
		B.full_name AS BRANCH_NAME,
		CAST(T.STATE_CODE || ' ' || T.STATE_NUMBER || ' (' || TM.FULL_NAME || ')' AS VARCHAR) AS TRANSPORT_INFO,
		P.FULL_NAME AS DRIVER,
		SUM(GE.TOTAL_SUM) AS TOTAL_SUM,
		GE.LIMIT_IS_OVER AS IS_OVER_LIMIT
	FROM DOC_TRANSPORT_SETTING AS TS
	JOIN HL_TRANSPORT AS T ON TS.transport_id = T.id
	JOIN INFO_TRANSPORT_MODEL AS TM ON T.transport_model_id = TM.id
	JOIN HL_DRIVER AS D ON TS.driver_id = D.id
	JOIN HL_PERSON AS P ON D.person_id = P.id
	LEFT JOIN HL_BRANCH AS B ON TS.branch_id = B.id
	JOIN GENERAL_EXPENSES AS GE ON TS.transport_id = GE.TRANSPORT_ID AND TS.driver_id = GE.DRIVER_ID
	WHERE TS.STATUS_ID = 3 AND
		GE.LIMIT_IS_OVER = TRUE AND
		(TS.BRANCH_ID = p_branch_id OR p_branch_id IS NULL) AND
		(TS.TRANSPORT_ID = p_transport_id OR p_transport_id IS NULL) AND
		(TS.DRIVER_ID = p_driver_id OR p_driver_id IS NULL)
	GROUP BY TS.transport_id, TS.driver_id, TS.branch_id, B.full_name, TM.full_name, T.state_code, T.state_number, P.full_name, GE.LIMIT_IS_OVER;
END;
$BODY$;

ALTER FUNCTION public.get_total_expense_over_limit(integer, integer, integer, timestamp without time zone, timestamp without time zone)
    OWNER TO postgres;
